// Copyright [2015] [Centers for Disease Control and Prevention] 
// Licensed under the CDC Custom Open Source License 1 (the 'License'); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at
// 
//   http://t.cdc.gov/O4O
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ContentServices_IntegrationModel", "FK_Media_MediaTypes1", "MediaType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.ThumbnailProvider.Model.MediaType), "Medium", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.ThumbnailProvider.Model.Media_Media), true)]
[assembly: EdmRelationshipAttribute("ContentServices_IntegrationModel", "FK_media_Thumbnail_ref_media_Media", "Medium", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.ThumbnailProvider.Model.Media_Media), "Thumbnail", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gov.Hhs.Cdc.ThumbnailProvider.Model.Thumbnail), true)]

#endregion

namespace Gov.Hhs.Cdc.ThumbnailProvider.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MediaDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MediaDbEntities object using the connection string found in the 'MediaDbEntities' section of the application configuration file.
        /// </summary>
        public MediaDbEntities() : base("name=MediaDbEntities", "MediaDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaDbEntities object.
        /// </summary>
        public MediaDbEntities(string connectionString) : base(connectionString, "MediaDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaDbEntities object.
        /// </summary>
        public MediaDbEntities(EntityConnection connection) : base(connection, "MediaDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaType> MediaTypes
        {
            get
            {
                if ((_MediaTypes == null))
                {
                    _MediaTypes = base.CreateObjectSet<MediaType>("MediaTypes");
                }
                return _MediaTypes;
            }
        }
        private ObjectSet<MediaType> _MediaTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Thumbnail> Thumbnails
        {
            get
            {
                if ((_Thumbnails == null))
                {
                    _Thumbnails = base.CreateObjectSet<Thumbnail>("Thumbnails");
                }
                return _Thumbnails;
            }
        }
        private ObjectSet<Thumbnail> _Thumbnails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaThumbnail> MediaThumbnails
        {
            get
            {
                if ((_MediaThumbnails == null))
                {
                    _MediaThumbnails = base.CreateObjectSet<MediaThumbnail>("MediaThumbnails");
                }
                return _MediaThumbnails;
            }
        }
        private ObjectSet<MediaThumbnail> _MediaThumbnails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Media_Media> Media_Media
        {
            get
            {
                if ((_Media_Media == null))
                {
                    _Media_Media = base.CreateObjectSet<Media_Media>("Media_Media");
                }
                return _Media_Media;
            }
        }
        private ObjectSet<Media_Media> _Media_Media;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaTypes(MediaType mediaType)
        {
            base.AddObject("MediaTypes", mediaType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Thumbnails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThumbnails(Thumbnail thumbnail)
        {
            base.AddObject("Thumbnails", thumbnail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaThumbnails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaThumbnails(MediaThumbnail mediaThumbnail)
        {
            base.AddObject("MediaThumbnails", mediaThumbnail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media_Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia_Media(Media_Media media_Media)
        {
            base.AddObject("Media_Media", media_Media);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_IntegrationModel", Name="Media_Media")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Media_Media : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Media_Media object.
        /// </summary>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="mediaGuid">Initial value of the MediaGuid property.</param>
        /// <param name="sourceCode">Initial value of the SourceCode property.</param>
        /// <param name="languageCode">Initial value of the LanguageCode property.</param>
        /// <param name="mediaTypeCode">Initial value of the MediaTypeCode property.</param>
        /// <param name="characterEncodingCode">Initial value of the CharacterEncodingCode property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="ratingMinimum">Initial value of the RatingMinimum property.</param>
        /// <param name="ratingMaximum">Initial value of the RatingMaximum property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        /// <param name="mediaStatusCode">Initial value of the MediaStatusCode property.</param>
        public static Media_Media CreateMedia_Media(global::System.Int32 mediaId, global::System.Guid mediaGuid, global::System.String sourceCode, global::System.String languageCode, global::System.String mediaTypeCode, global::System.String characterEncodingCode, global::System.String title, global::System.Int32 ratingMinimum, global::System.Int32 ratingMaximum, global::System.Byte[] rowVersion, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime, global::System.String mediaStatusCode)
        {
            Media_Media media_Media = new Media_Media();
            media_Media.MediaId = mediaId;
            media_Media.MediaGuid = mediaGuid;
            media_Media.SourceCode = sourceCode;
            media_Media.LanguageCode = languageCode;
            media_Media.MediaTypeCode = mediaTypeCode;
            media_Media.CharacterEncodingCode = characterEncodingCode;
            media_Media.Title = title;
            media_Media.RatingMinimum = ratingMinimum;
            media_Media.RatingMaximum = ratingMaximum;
            media_Media.RowVersion = rowVersion;
            media_Media.CreatedByGuid = createdByGuid;
            media_Media.CreatedDateTime = createdDateTime;
            media_Media.ModifiedByGuid = modifiedByGuid;
            media_Media.ModifiedDateTime = modifiedDateTime;
            media_Media.MediaStatusCode = mediaStatusCode;
            return media_Media;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaId
        {
            get
            {
                return _MediaId;
            }
            set
            {
                if (_MediaId != value)
                {
                    OnMediaIdChanging(value);
                    ReportPropertyChanging("MediaId");
                    _MediaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaId");
                    OnMediaIdChanged();
                }
            }
        }
        private global::System.Int32 _MediaId;
        partial void OnMediaIdChanging(global::System.Int32 value);
        partial void OnMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MediaGuid
        {
            get
            {
                return _MediaGuid;
            }
            set
            {
                OnMediaGuidChanging(value);
                ReportPropertyChanging("MediaGuid");
                _MediaGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MediaGuid");
                OnMediaGuidChanged();
            }
        }
        private global::System.Guid _MediaGuid;
        partial void OnMediaGuidChanging(global::System.Guid value);
        partial void OnMediaGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExternalIdentifier
        {
            get
            {
                return _ExternalIdentifier;
            }
            set
            {
                OnExternalIdentifierChanging(value);
                ReportPropertyChanging("ExternalIdentifier");
                _ExternalIdentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExternalIdentifier");
                OnExternalIdentifierChanged();
            }
        }
        private global::System.String _ExternalIdentifier;
        partial void OnExternalIdentifierChanging(global::System.String value);
        partial void OnExternalIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SourceCode
        {
            get
            {
                return _SourceCode;
            }
            set
            {
                OnSourceCodeChanging(value);
                ReportPropertyChanging("SourceCode");
                _SourceCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SourceCode");
                OnSourceCodeChanged();
            }
        }
        private global::System.String _SourceCode;
        partial void OnSourceCodeChanging(global::System.String value);
        partial void OnSourceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OwningBusinessUnitId
        {
            get
            {
                return _OwningBusinessUnitId;
            }
            set
            {
                OnOwningBusinessUnitIdChanging(value);
                ReportPropertyChanging("OwningBusinessUnitId");
                _OwningBusinessUnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwningBusinessUnitId");
                OnOwningBusinessUnitIdChanged();
            }
        }
        private Nullable<global::System.Int32> _OwningBusinessUnitId;
        partial void OnOwningBusinessUnitIdChanging(Nullable<global::System.Int32> value);
        partial void OnOwningBusinessUnitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaintainingBusinessUnitId
        {
            get
            {
                return _MaintainingBusinessUnitId;
            }
            set
            {
                OnMaintainingBusinessUnitIdChanging(value);
                ReportPropertyChanging("MaintainingBusinessUnitId");
                _MaintainingBusinessUnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintainingBusinessUnitId");
                OnMaintainingBusinessUnitIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MaintainingBusinessUnitId;
        partial void OnMaintainingBusinessUnitIdChanging(Nullable<global::System.Int32> value);
        partial void OnMaintainingBusinessUnitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageCode
        {
            get
            {
                return _LanguageCode;
            }
            set
            {
                OnLanguageCodeChanging(value);
                ReportPropertyChanging("LanguageCode");
                _LanguageCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LanguageCode");
                OnLanguageCodeChanged();
            }
        }
        private global::System.String _LanguageCode;
        partial void OnLanguageCodeChanging(global::System.String value);
        partial void OnLanguageCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaTypeCode
        {
            get
            {
                return _MediaTypeCode;
            }
            set
            {
                OnMediaTypeCodeChanging(value);
                ReportPropertyChanging("MediaTypeCode");
                _MediaTypeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MediaTypeCode");
                OnMediaTypeCodeChanged();
            }
        }
        private global::System.String _MediaTypeCode;
        partial void OnMediaTypeCodeChanging(global::System.String value);
        partial void OnMediaTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MimeTypeCode
        {
            get
            {
                return _MimeTypeCode;
            }
            set
            {
                OnMimeTypeCodeChanging(value);
                ReportPropertyChanging("MimeTypeCode");
                _MimeTypeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MimeTypeCode");
                OnMimeTypeCodeChanged();
            }
        }
        private global::System.String _MimeTypeCode;
        partial void OnMimeTypeCodeChanging(global::System.String value);
        partial void OnMimeTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CharacterEncodingCode
        {
            get
            {
                return _CharacterEncodingCode;
            }
            set
            {
                OnCharacterEncodingCodeChanging(value);
                ReportPropertyChanging("CharacterEncodingCode");
                _CharacterEncodingCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CharacterEncodingCode");
                OnCharacterEncodingCodeChanged();
            }
        }
        private global::System.String _CharacterEncodingCode;
        partial void OnCharacterEncodingCodeChanging(global::System.String value);
        partial void OnCharacterEncodingCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitle
        {
            get
            {
                return _SubTitle;
            }
            set
            {
                OnSubTitleChanging(value);
                ReportPropertyChanging("SubTitle");
                _SubTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitle");
                OnSubTitleChanged();
            }
        }
        private global::System.String _SubTitle;
        partial void OnSubTitleChanging(global::System.String value);
        partial void OnSubTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceUrl
        {
            get
            {
                return _SourceUrl;
            }
            set
            {
                OnSourceUrlChanging(value);
                ReportPropertyChanging("SourceUrl");
                _SourceUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceUrl");
                OnSourceUrlChanged();
            }
        }
        private global::System.String _SourceUrl;
        partial void OnSourceUrlChanging(global::System.String value);
        partial void OnSourceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TargetUrl
        {
            get
            {
                return _TargetUrl;
            }
            set
            {
                OnTargetUrlChanging(value);
                ReportPropertyChanging("TargetUrl");
                _TargetUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TargetUrl");
                OnTargetUrlChanged();
            }
        }
        private global::System.String _TargetUrl;
        partial void OnTargetUrlChanging(global::System.String value);
        partial void OnTargetUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AlternateText
        {
            get
            {
                return _AlternateText;
            }
            set
            {
                OnAlternateTextChanging(value);
                ReportPropertyChanging("AlternateText");
                _AlternateText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AlternateText");
                OnAlternateTextChanged();
            }
        }
        private global::System.String _AlternateText;
        partial void OnAlternateTextChanging(global::System.String value);
        partial void OnAlternateTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoScriptText
        {
            get
            {
                return _NoScriptText;
            }
            set
            {
                OnNoScriptTextChanging(value);
                ReportPropertyChanging("NoScriptText");
                _NoScriptText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoScriptText");
                OnNoScriptTextChanged();
            }
        }
        private global::System.String _NoScriptText;
        partial void OnNoScriptTextChanging(global::System.String value);
        partial void OnNoScriptTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FeaturedText
        {
            get
            {
                return _FeaturedText;
            }
            set
            {
                OnFeaturedTextChanging(value);
                ReportPropertyChanging("FeaturedText");
                _FeaturedText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FeaturedText");
                OnFeaturedTextChanged();
            }
        }
        private global::System.String _FeaturedText;
        partial void OnFeaturedTextChanging(global::System.String value);
        partial void OnFeaturedTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Int32> _Length;
        partial void OnLengthChanging(Nullable<global::System.Int32> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RatingOverride
        {
            get
            {
                return _RatingOverride;
            }
            set
            {
                OnRatingOverrideChanging(value);
                ReportPropertyChanging("RatingOverride");
                _RatingOverride = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingOverride");
                OnRatingOverrideChanged();
            }
        }
        private Nullable<global::System.Int32> _RatingOverride;
        partial void OnRatingOverrideChanging(Nullable<global::System.Int32> value);
        partial void OnRatingOverrideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RatingMinimum
        {
            get
            {
                return _RatingMinimum;
            }
            set
            {
                OnRatingMinimumChanging(value);
                ReportPropertyChanging("RatingMinimum");
                _RatingMinimum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingMinimum");
                OnRatingMinimumChanged();
            }
        }
        private global::System.Int32 _RatingMinimum;
        partial void OnRatingMinimumChanging(global::System.Int32 value);
        partial void OnRatingMinimumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RatingMaximum
        {
            get
            {
                return _RatingMaximum;
            }
            set
            {
                OnRatingMaximumChanging(value);
                ReportPropertyChanging("RatingMaximum");
                _RatingMaximum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingMaximum");
                OnRatingMaximumChanged();
            }
        }
        private global::System.Int32 _RatingMaximum;
        partial void OnRatingMaximumChanging(global::System.Int32 value);
        partial void OnRatingMaximumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmbedParameters
        {
            get
            {
                return _EmbedParameters;
            }
            set
            {
                OnEmbedParametersChanging(value);
                ReportPropertyChanging("EmbedParameters");
                _EmbedParameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmbedParameters");
                OnEmbedParametersChanged();
            }
        }
        private global::System.String _EmbedParameters;
        partial void OnEmbedParametersChanging(global::System.String value);
        partial void OnEmbedParametersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastReviewedDateTime
        {
            get
            {
                return _LastReviewedDateTime;
            }
            set
            {
                OnLastReviewedDateTimeChanging(value);
                ReportPropertyChanging("LastReviewedDateTime");
                _LastReviewedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastReviewedDateTime");
                OnLastReviewedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastReviewedDateTime;
        partial void OnLastReviewedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastReviewedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PublishedDateTime
        {
            get
            {
                return _PublishedDateTime;
            }
            set
            {
                OnPublishedDateTimeChanging(value);
                ReportPropertyChanging("PublishedDateTime");
                _PublishedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishedDateTime");
                OnPublishedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PublishedDateTime;
        partial void OnPublishedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPublishedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PersistentURLToken
        {
            get
            {
                return _PersistentURLToken;
            }
            set
            {
                OnPersistentURLTokenChanging(value);
                ReportPropertyChanging("PersistentURLToken");
                _PersistentURLToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PersistentURLToken");
                OnPersistentURLTokenChanged();
            }
        }
        private global::System.String _PersistentURLToken;
        partial void OnPersistentURLTokenChanging(global::System.String value);
        partial void OnPersistentURLTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaStatusCode
        {
            get
            {
                return _MediaStatusCode;
            }
            set
            {
                OnMediaStatusCodeChanging(value);
                ReportPropertyChanging("MediaStatusCode");
                _MediaStatusCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MediaStatusCode");
                OnMediaStatusCodeChanged();
            }
        }
        private global::System.String _MediaStatusCode;
        partial void OnMediaStatusCodeChanging(global::System.String value);
        partial void OnMediaStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainName
        {
            get
            {
                return _DomainName;
            }
            set
            {
                OnDomainNameChanging(value);
                ReportPropertyChanging("DomainName");
                _DomainName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainName");
                OnDomainNameChanged();
            }
        }
        private global::System.String _DomainName;
        partial void OnDomainNameChanging(global::System.String value);
        partial void OnDomainNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentAuthored
        {
            get
            {
                return _DateContentAuthored;
            }
            set
            {
                OnDateContentAuthoredChanging(value);
                ReportPropertyChanging("DateContentAuthored");
                _DateContentAuthored = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentAuthored");
                OnDateContentAuthoredChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentAuthored;
        partial void OnDateContentAuthoredChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentAuthoredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentUpdated
        {
            get
            {
                return _DateContentUpdated;
            }
            set
            {
                OnDateContentUpdatedChanging(value);
                ReportPropertyChanging("DateContentUpdated");
                _DateContentUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentUpdated");
                OnDateContentUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentUpdated;
        partial void OnDateContentUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentPublished
        {
            get
            {
                return _DateContentPublished;
            }
            set
            {
                OnDateContentPublishedChanging(value);
                ReportPropertyChanging("DateContentPublished");
                _DateContentPublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentPublished");
                OnDateContentPublishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentPublished;
        partial void OnDateContentPublishedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentReviewed
        {
            get
            {
                return _DateContentReviewed;
            }
            set
            {
                OnDateContentReviewedChanging(value);
                ReportPropertyChanging("DateContentReviewed");
                _DateContentReviewed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentReviewed");
                OnDateContentReviewedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentReviewed;
        partial void OnDateContentReviewedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentReviewedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSyndicationCaptured
        {
            get
            {
                return _DateSyndicationCaptured;
            }
            set
            {
                OnDateSyndicationCapturedChanging(value);
                ReportPropertyChanging("DateSyndicationCaptured");
                _DateSyndicationCaptured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSyndicationCaptured");
                OnDateSyndicationCapturedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSyndicationCaptured;
        partial void OnDateSyndicationCapturedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSyndicationCapturedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSyndicationUpdated
        {
            get
            {
                return _DateSyndicationUpdated;
            }
            set
            {
                OnDateSyndicationUpdatedChanging(value);
                ReportPropertyChanging("DateSyndicationUpdated");
                _DateSyndicationUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSyndicationUpdated");
                OnDateSyndicationUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSyndicationUpdated;
        partial void OnDateSyndicationUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSyndicationUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSyndicationVisible
        {
            get
            {
                return _DateSyndicationVisible;
            }
            set
            {
                OnDateSyndicationVisibleChanging(value);
                ReportPropertyChanging("DateSyndicationVisible");
                _DateSyndicationVisible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSyndicationVisible");
                OnDateSyndicationVisibleChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSyndicationVisible;
        partial void OnDateSyndicationVisibleChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSyndicationVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmbedCode
        {
            get
            {
                return _EmbedCode;
            }
            set
            {
                OnEmbedCodeChanging(value);
                ReportPropertyChanging("EmbedCode");
                _EmbedCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmbedCode");
                OnEmbedCodeChanged();
            }
        }
        private global::System.String _EmbedCode;
        partial void OnEmbedCodeChanging(global::System.String value);
        partial void OnEmbedCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PageCount
        {
            get
            {
                return _PageCount;
            }
            set
            {
                OnPageCountChanging(value);
                ReportPropertyChanging("PageCount");
                _PageCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageCount");
                OnPageCountChanged();
            }
        }
        private Nullable<global::System.Int32> _PageCount;
        partial void OnPageCountChanging(Nullable<global::System.Int32> value);
        partial void OnPageCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataSize
        {
            get
            {
                return _DataSize;
            }
            set
            {
                OnDataSizeChanging(value);
                ReportPropertyChanging("DataSize");
                _DataSize = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataSize");
                OnDataSizeChanged();
            }
        }
        private global::System.String _DataSize;
        partial void OnDataSizeChanging(global::System.String value);
        partial void OnDataSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtractionClasses
        {
            get
            {
                return _ExtractionClasses;
            }
            set
            {
                OnExtractionClassesChanging(value);
                ReportPropertyChanging("ExtractionClasses");
                _ExtractionClasses = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtractionClasses");
                OnExtractionClassesChanged();
            }
        }
        private global::System.String _ExtractionClasses;
        partial void OnExtractionClassesChanging(global::System.String value);
        partial void OnExtractionClassesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtractionElementIds
        {
            get
            {
                return _ExtractionElementIds;
            }
            set
            {
                OnExtractionElementIdsChanging(value);
                ReportPropertyChanging("ExtractionElementIds");
                _ExtractionElementIds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtractionElementIds");
                OnExtractionElementIdsChanged();
            }
        }
        private global::System.String _ExtractionElementIds;
        partial void OnExtractionElementIdsChanging(global::System.String value);
        partial void OnExtractionElementIdsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtractionXpath
        {
            get
            {
                return _ExtractionXpath;
            }
            set
            {
                OnExtractionXpathChanging(value);
                ReportPropertyChanging("ExtractionXpath");
                _ExtractionXpath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtractionXpath");
                OnExtractionXpathChanged();
            }
        }
        private global::System.String _ExtractionXpath;
        partial void OnExtractionXpathChanging(global::System.String value);
        partial void OnExtractionXpathChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_IntegrationModel", "FK_Media_MediaTypes1", "MediaType")]
        public MediaType MediaType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MediaType>("ContentServices_IntegrationModel.FK_Media_MediaTypes1", "MediaType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MediaType>("ContentServices_IntegrationModel.FK_Media_MediaTypes1", "MediaType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MediaType> MediaTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MediaType>("ContentServices_IntegrationModel.FK_Media_MediaTypes1", "MediaType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MediaType>("ContentServices_IntegrationModel.FK_Media_MediaTypes1", "MediaType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_IntegrationModel", "FK_media_Thumbnail_ref_media_Media", "Thumbnail")]
        public Thumbnail Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Thumbnail>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Thumbnail").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Thumbnail>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Thumbnail").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Thumbnail> ThumbnailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Thumbnail>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Thumbnail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Thumbnail>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Thumbnail", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_IntegrationModel", Name="MediaThumbnail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaThumbnail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaThumbnail object.
        /// </summary>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="isDefault">Initial value of the isDefault property.</param>
        public static MediaThumbnail CreateMediaThumbnail(global::System.Int32 mediaId, global::System.String isDefault)
        {
            MediaThumbnail mediaThumbnail = new MediaThumbnail();
            mediaThumbnail.MediaId = mediaId;
            mediaThumbnail.isDefault = isDefault;
            return mediaThumbnail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaId
        {
            get
            {
                return _MediaId;
            }
            set
            {
                if (_MediaId != value)
                {
                    OnMediaIdChanging(value);
                    ReportPropertyChanging("MediaId");
                    _MediaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaId");
                    OnMediaIdChanged();
                }
            }
        }
        private global::System.Int32 _MediaId;
        partial void OnMediaIdChanging(global::System.Int32 value);
        partial void OnMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ThumbnailImage
        {
            get
            {
                return StructuralObject.GetValidValue(_ThumbnailImage);
            }
            set
            {
                OnThumbnailImageChanging(value);
                ReportPropertyChanging("ThumbnailImage");
                _ThumbnailImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbnailImage");
                OnThumbnailImageChanged();
            }
        }
        private global::System.Byte[] _ThumbnailImage;
        partial void OnThumbnailImageChanging(global::System.Byte[] value);
        partial void OnThumbnailImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String isDefault
        {
            get
            {
                return _isDefault;
            }
            set
            {
                if (_isDefault != value)
                {
                    OnisDefaultChanging(value);
                    ReportPropertyChanging("isDefault");
                    _isDefault = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("isDefault");
                    OnisDefaultChanged();
                }
            }
        }
        private global::System.String _isDefault;
        partial void OnisDefaultChanging(global::System.String value);
        partial void OnisDefaultChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_IntegrationModel", Name="MediaType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaType object.
        /// </summary>
        /// <param name="mediaTypeCode">Initial value of the MediaTypeCode property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="displayOrdinal">Initial value of the DisplayOrdinal property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="display">Initial value of the Display property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        public static MediaType CreateMediaType(global::System.String mediaTypeCode, global::System.String description, global::System.Int32 displayOrdinal, global::System.String active, global::System.String display, global::System.DateTime createdDateTime, global::System.Guid createdByGuid, global::System.DateTime modifiedDateTime, global::System.Guid modifiedByGuid)
        {
            MediaType mediaType = new MediaType();
            mediaType.MediaTypeCode = mediaTypeCode;
            mediaType.Description = description;
            mediaType.DisplayOrdinal = displayOrdinal;
            mediaType.Active = active;
            mediaType.Display = display;
            mediaType.CreatedDateTime = createdDateTime;
            mediaType.CreatedByGuid = createdByGuid;
            mediaType.ModifiedDateTime = modifiedDateTime;
            mediaType.ModifiedByGuid = modifiedByGuid;
            return mediaType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaTypeCode
        {
            get
            {
                return _MediaTypeCode;
            }
            set
            {
                if (_MediaTypeCode != value)
                {
                    OnMediaTypeCodeChanging(value);
                    ReportPropertyChanging("MediaTypeCode");
                    _MediaTypeCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MediaTypeCode");
                    OnMediaTypeCodeChanged();
                }
            }
        }
        private global::System.String _MediaTypeCode;
        partial void OnMediaTypeCodeChanging(global::System.String value);
        partial void OnMediaTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DisplayOrdinal
        {
            get
            {
                return _DisplayOrdinal;
            }
            set
            {
                OnDisplayOrdinalChanging(value);
                ReportPropertyChanging("DisplayOrdinal");
                _DisplayOrdinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DisplayOrdinal");
                OnDisplayOrdinalChanged();
            }
        }
        private global::System.Int32 _DisplayOrdinal;
        partial void OnDisplayOrdinalChanging(global::System.Int32 value);
        partial void OnDisplayOrdinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.String _Active;
        partial void OnActiveChanging(global::System.String value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmbedParameters
        {
            get
            {
                return _EmbedParameters;
            }
            set
            {
                OnEmbedParametersChanging(value);
                ReportPropertyChanging("EmbedParameters");
                _EmbedParameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmbedParameters");
                OnEmbedParametersChanged();
            }
        }
        private global::System.String _EmbedParameters;
        partial void OnEmbedParametersChanging(global::System.String value);
        partial void OnEmbedParametersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Display
        {
            get
            {
                return _Display;
            }
            set
            {
                OnDisplayChanging(value);
                ReportPropertyChanging("Display");
                _Display = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Display");
                OnDisplayChanged();
            }
        }
        private global::System.String _Display;
        partial void OnDisplayChanging(global::System.String value);
        partial void OnDisplayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbBrowserHeight
        {
            get
            {
                return _ThumbBrowserHeight;
            }
            set
            {
                OnThumbBrowserHeightChanging(value);
                ReportPropertyChanging("ThumbBrowserHeight");
                _ThumbBrowserHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbBrowserHeight");
                OnThumbBrowserHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbBrowserHeight;
        partial void OnThumbBrowserHeightChanging(Nullable<global::System.Int32> value);
        partial void OnThumbBrowserHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbBrowserWidth
        {
            get
            {
                return _ThumbBrowserWidth;
            }
            set
            {
                OnThumbBrowserWidthChanging(value);
                ReportPropertyChanging("ThumbBrowserWidth");
                _ThumbBrowserWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbBrowserWidth");
                OnThumbBrowserWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbBrowserWidth;
        partial void OnThumbBrowserWidthChanging(Nullable<global::System.Int32> value);
        partial void OnThumbBrowserWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbCropHeight
        {
            get
            {
                return _ThumbCropHeight;
            }
            set
            {
                OnThumbCropHeightChanging(value);
                ReportPropertyChanging("ThumbCropHeight");
                _ThumbCropHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbCropHeight");
                OnThumbCropHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbCropHeight;
        partial void OnThumbCropHeightChanging(Nullable<global::System.Int32> value);
        partial void OnThumbCropHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbCropLeft
        {
            get
            {
                return _ThumbCropLeft;
            }
            set
            {
                OnThumbCropLeftChanging(value);
                ReportPropertyChanging("ThumbCropLeft");
                _ThumbCropLeft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbCropLeft");
                OnThumbCropLeftChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbCropLeft;
        partial void OnThumbCropLeftChanging(Nullable<global::System.Int32> value);
        partial void OnThumbCropLeftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbCropTop
        {
            get
            {
                return _ThumbCropTop;
            }
            set
            {
                OnThumbCropTopChanging(value);
                ReportPropertyChanging("ThumbCropTop");
                _ThumbCropTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbCropTop");
                OnThumbCropTopChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbCropTop;
        partial void OnThumbCropTopChanging(Nullable<global::System.Int32> value);
        partial void OnThumbCropTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbCropWidth
        {
            get
            {
                return _ThumbCropWidth;
            }
            set
            {
                OnThumbCropWidthChanging(value);
                ReportPropertyChanging("ThumbCropWidth");
                _ThumbCropWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbCropWidth");
                OnThumbCropWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbCropWidth;
        partial void OnThumbCropWidthChanging(Nullable<global::System.Int32> value);
        partial void OnThumbCropWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ThumbPause
        {
            get
            {
                return _ThumbPause;
            }
            set
            {
                OnThumbPauseChanging(value);
                ReportPropertyChanging("ThumbPause");
                _ThumbPause = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThumbPause");
                OnThumbPauseChanged();
            }
        }
        private Nullable<global::System.Int32> _ThumbPause;
        partial void OnThumbPauseChanging(Nullable<global::System.Int32> value);
        partial void OnThumbPauseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Thumbnail
        {
            get
            {
                return StructuralObject.GetValidValue(_Thumbnail);
            }
            set
            {
                OnThumbnailChanging(value);
                ReportPropertyChanging("Thumbnail");
                _Thumbnail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Thumbnail");
                OnThumbnailChanged();
            }
        }
        private global::System.Byte[] _Thumbnail;
        partial void OnThumbnailChanging(global::System.Byte[] value);
        partial void OnThumbnailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_IntegrationModel", "FK_Media_MediaTypes1", "Medium")]
        public EntityCollection<Media_Media> Media1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Media_Media>("ContentServices_IntegrationModel.FK_Media_MediaTypes1", "Medium");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Media_Media>("ContentServices_IntegrationModel.FK_Media_MediaTypes1", "Medium", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_IntegrationModel", Name="Thumbnail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Thumbnail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Thumbnail object.
        /// </summary>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static Thumbnail CreateThumbnail(global::System.Int32 mediaId, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime)
        {
            Thumbnail thumbnail = new Thumbnail();
            thumbnail.MediaId = mediaId;
            thumbnail.CreatedByGuid = createdByGuid;
            thumbnail.CreatedDateTime = createdDateTime;
            thumbnail.ModifiedByGuid = modifiedByGuid;
            thumbnail.ModifiedDateTime = modifiedDateTime;
            return thumbnail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaId
        {
            get
            {
                return _MediaId;
            }
            set
            {
                if (_MediaId != value)
                {
                    OnMediaIdChanging(value);
                    ReportPropertyChanging("MediaId");
                    _MediaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaId");
                    OnMediaIdChanged();
                }
            }
        }
        private global::System.Int32 _MediaId;
        partial void OnMediaIdChanging(global::System.Int32 value);
        partial void OnMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ThumbnailImage
        {
            get
            {
                return StructuralObject.GetValidValue(_ThumbnailImage);
            }
            set
            {
                OnThumbnailImageChanging(value);
                ReportPropertyChanging("ThumbnailImage");
                _ThumbnailImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThumbnailImage");
                OnThumbnailImageChanged();
            }
        }
        private global::System.Byte[] _ThumbnailImage;
        partial void OnThumbnailImageChanging(global::System.Byte[] value);
        partial void OnThumbnailImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_IntegrationModel", "FK_media_Thumbnail_ref_media_Media", "Medium")]
        public Media_Media Medium1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Media_Media>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Medium").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Media_Media>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Medium").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Media_Media> Medium1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Media_Media>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Medium");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Media_Media>("ContentServices_IntegrationModel.FK_media_Thumbnail_ref_media_Media", "Medium", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
