// Copyright [2015] [Centers for Disease Control and Prevention] 
// Licensed under the CDC Custom Open Source License 1 (the 'License'); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at
// 
//   http://t.cdc.gov/O4O
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ContentServicesModel", "FK_ApplicationEnvironments_Applications", "Application", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.Application), "ApplicationEnvironment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.ApplicationEnvironment), true)]
[assembly: EdmRelationshipAttribute("ContentServicesModel", "FK_ApplicationEnvironments_EnvironmentDatabases", "EnvironmentDatabas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.EnvironmentDatabas), "ApplicationEnvironment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.ApplicationEnvironment), true)]
[assembly: EdmRelationshipAttribute("ContentServicesModel", "FK_EnvironmentDatabases_Environments", "Environment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.Environment), "EnvironmentDatabas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.EnvironmentDatabas), true)]
[assembly: EdmRelationshipAttribute("ContentServicesModel", "FK_FilterCriterionDate_FilterCriterion", "FilterCriterion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.FilterCriterion), "FilterCriterionDate", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gov.Hhs.Cdc.DataSource.Dal.Cs.FilterCriterionDate), true)]

#endregion

namespace Gov.Hhs.Cdc.DataSource.Dal.Cs
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ContentServicesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ContentServicesEntities object using the connection string found in the 'ContentServicesEntities' section of the application configuration file.
        /// </summary>
        public ContentServicesEntities() : base("name=ContentServicesEntities", "ContentServicesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContentServicesEntities object.
        /// </summary>
        public ContentServicesEntities(string connectionString) : base(connectionString, "ContentServicesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContentServicesEntities object.
        /// </summary>
        public ContentServicesEntities(EntityConnection connection) : base(connection, "ContentServicesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApplicationEnvironment> ApplicationEnvironments
        {
            get
            {
                if ((_ApplicationEnvironments == null))
                {
                    _ApplicationEnvironments = base.CreateObjectSet<ApplicationEnvironment>("ApplicationEnvironments");
                }
                return _ApplicationEnvironments;
            }
        }
        private ObjectSet<ApplicationEnvironment> _ApplicationEnvironments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EnvironmentDatabas> EnvironmentDatabases
        {
            get
            {
                if ((_EnvironmentDatabases == null))
                {
                    _EnvironmentDatabases = base.CreateObjectSet<EnvironmentDatabas>("EnvironmentDatabases");
                }
                return _EnvironmentDatabases;
            }
        }
        private ObjectSet<EnvironmentDatabas> _EnvironmentDatabases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Environment> Environments
        {
            get
            {
                if ((_Environments == null))
                {
                    _Environments = base.CreateObjectSet<Environment>("Environments");
                }
                return _Environments;
            }
        }
        private ObjectSet<Environment> _Environments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Application> Applications
        {
            get
            {
                if ((_Applications == null))
                {
                    _Applications = base.CreateObjectSet<Application>("Applications");
                }
                return _Applications;
            }
        }
        private ObjectSet<Application> _Applications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FilterCriterion> FilterCriterions
        {
            get
            {
                if ((_FilterCriterions == null))
                {
                    _FilterCriterions = base.CreateObjectSet<FilterCriterion>("FilterCriterions");
                }
                return _FilterCriterions;
            }
        }
        private ObjectSet<FilterCriterion> _FilterCriterions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FilterCriterionDate> FilterCriterionDates
        {
            get
            {
                if ((_FilterCriterionDates == null))
                {
                    _FilterCriterionDates = base.CreateObjectSet<FilterCriterionDate>("FilterCriterionDates");
                }
                return _FilterCriterionDates;
            }
        }
        private ObjectSet<FilterCriterionDate> _FilterCriterionDates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReportPlan> ReportPlans
        {
            get
            {
                if ((_ReportPlans == null))
                {
                    _ReportPlans = base.CreateObjectSet<ReportPlan>("ReportPlans");
                }
                return _ReportPlans;
            }
        }
        private ObjectSet<ReportPlan> _ReportPlans;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApplicationEnvironments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplicationEnvironments(ApplicationEnvironment applicationEnvironment)
        {
            base.AddObject("ApplicationEnvironments", applicationEnvironment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EnvironmentDatabases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnvironmentDatabases(EnvironmentDatabas environmentDatabas)
        {
            base.AddObject("EnvironmentDatabases", environmentDatabas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Environments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnvironments(Environment environment)
        {
            base.AddObject("Environments", environment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Applications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApplications(Application application)
        {
            base.AddObject("Applications", application);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FilterCriterions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFilterCriterions(FilterCriterion filterCriterion)
        {
            base.AddObject("FilterCriterions", filterCriterion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FilterCriterionDates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFilterCriterionDates(FilterCriterionDate filterCriterionDate)
        {
            base.AddObject("FilterCriterionDates", filterCriterionDate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReportPlans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReportPlans(ReportPlan reportPlan)
        {
            base.AddObject("ReportPlans", reportPlan);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="Application")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Application : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Application object.
        /// </summary>
        /// <param name="applicationCode">Initial value of the ApplicationCode property.</param>
        /// <param name="applicationName">Initial value of the ApplicationName property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static Application CreateApplication(global::System.String applicationCode, global::System.String applicationName, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            Application application = new Application();
            application.ApplicationCode = applicationCode;
            application.ApplicationName = applicationName;
            application.CreatedDateTime = createdDateTime;
            application.ModifiedDateTime = modifiedDateTime;
            return application;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationCode
        {
            get
            {
                return _ApplicationCode;
            }
            set
            {
                if (_ApplicationCode != value)
                {
                    OnApplicationCodeChanging(value);
                    ReportPropertyChanging("ApplicationCode");
                    _ApplicationCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ApplicationCode");
                    OnApplicationCodeChanged();
                }
            }
        }
        private global::System.String _ApplicationCode;
        partial void OnApplicationCodeChanging(global::System.String value);
        partial void OnApplicationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationName
        {
            get
            {
                return _ApplicationName;
            }
            set
            {
                OnApplicationNameChanging(value);
                ReportPropertyChanging("ApplicationName");
                _ApplicationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApplicationName");
                OnApplicationNameChanged();
            }
        }
        private global::System.String _ApplicationName;
        partial void OnApplicationNameChanging(global::System.String value);
        partial void OnApplicationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataSourceManagerDll
        {
            get
            {
                return _DataSourceManagerDll;
            }
            set
            {
                OnDataSourceManagerDllChanging(value);
                ReportPropertyChanging("DataSourceManagerDll");
                _DataSourceManagerDll = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataSourceManagerDll");
                OnDataSourceManagerDllChanged();
            }
        }
        private global::System.String _DataSourceManagerDll;
        partial void OnDataSourceManagerDllChanging(global::System.String value);
        partial void OnDataSourceManagerDllChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataSourceManagerClass
        {
            get
            {
                return _DataSourceManagerClass;
            }
            set
            {
                OnDataSourceManagerClassChanging(value);
                ReportPropertyChanging("DataSourceManagerClass");
                _DataSourceManagerClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataSourceManagerClass");
                OnDataSourceManagerClassChanged();
            }
        }
        private global::System.String _DataSourceManagerClass;
        partial void OnDataSourceManagerClassChanging(global::System.String value);
        partial void OnDataSourceManagerClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_ApplicationEnvironments_Applications", "ApplicationEnvironment")]
        public EntityCollection<ApplicationEnvironment> ApplicationEnvironments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEnvironment>("ContentServicesModel.FK_ApplicationEnvironments_Applications", "ApplicationEnvironment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEnvironment>("ContentServicesModel.FK_ApplicationEnvironments_Applications", "ApplicationEnvironment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="ApplicationEnvironment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApplicationEnvironment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApplicationEnvironment object.
        /// </summary>
        /// <param name="applicationCode">Initial value of the ApplicationCode property.</param>
        /// <param name="environmentCode">Initial value of the EnvironmentCode property.</param>
        /// <param name="databaseCode">Initial value of the DatabaseCode property.</param>
        /// <param name="isDefault">Initial value of the IsDefault property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static ApplicationEnvironment CreateApplicationEnvironment(global::System.String applicationCode, global::System.String environmentCode, global::System.String databaseCode, global::System.String isDefault, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            ApplicationEnvironment applicationEnvironment = new ApplicationEnvironment();
            applicationEnvironment.ApplicationCode = applicationCode;
            applicationEnvironment.EnvironmentCode = environmentCode;
            applicationEnvironment.DatabaseCode = databaseCode;
            applicationEnvironment.IsDefault = isDefault;
            applicationEnvironment.CreatedDateTime = createdDateTime;
            applicationEnvironment.ModifiedDateTime = modifiedDateTime;
            return applicationEnvironment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationCode
        {
            get
            {
                return _ApplicationCode;
            }
            set
            {
                if (_ApplicationCode != value)
                {
                    OnApplicationCodeChanging(value);
                    ReportPropertyChanging("ApplicationCode");
                    _ApplicationCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ApplicationCode");
                    OnApplicationCodeChanged();
                }
            }
        }
        private global::System.String _ApplicationCode;
        partial void OnApplicationCodeChanging(global::System.String value);
        partial void OnApplicationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentCode
        {
            get
            {
                return _EnvironmentCode;
            }
            set
            {
                if (_EnvironmentCode != value)
                {
                    OnEnvironmentCodeChanging(value);
                    ReportPropertyChanging("EnvironmentCode");
                    _EnvironmentCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EnvironmentCode");
                    OnEnvironmentCodeChanged();
                }
            }
        }
        private global::System.String _EnvironmentCode;
        partial void OnEnvironmentCodeChanging(global::System.String value);
        partial void OnEnvironmentCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DatabaseCode
        {
            get
            {
                return _DatabaseCode;
            }
            set
            {
                if (_DatabaseCode != value)
                {
                    OnDatabaseCodeChanging(value);
                    ReportPropertyChanging("DatabaseCode");
                    _DatabaseCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DatabaseCode");
                    OnDatabaseCodeChanged();
                }
            }
        }
        private global::System.String _DatabaseCode;
        partial void OnDatabaseCodeChanging(global::System.String value);
        partial void OnDatabaseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsDefault
        {
            get
            {
                return _IsDefault;
            }
            set
            {
                OnIsDefaultChanging(value);
                ReportPropertyChanging("IsDefault");
                _IsDefault = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsDefault");
                OnIsDefaultChanged();
            }
        }
        private global::System.String _IsDefault;
        partial void OnIsDefaultChanging(global::System.String value);
        partial void OnIsDefaultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_ApplicationEnvironments_Applications", "Application")]
        public Application Application
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Application>("ContentServicesModel.FK_ApplicationEnvironments_Applications", "Application").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Application>("ContentServicesModel.FK_ApplicationEnvironments_Applications", "Application").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Application> ApplicationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Application>("ContentServicesModel.FK_ApplicationEnvironments_Applications", "Application");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Application>("ContentServicesModel.FK_ApplicationEnvironments_Applications", "Application", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_ApplicationEnvironments_EnvironmentDatabases", "EnvironmentDatabas")]
        public EnvironmentDatabas EnvironmentDatabas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EnvironmentDatabas>("ContentServicesModel.FK_ApplicationEnvironments_EnvironmentDatabases", "EnvironmentDatabas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EnvironmentDatabas>("ContentServicesModel.FK_ApplicationEnvironments_EnvironmentDatabases", "EnvironmentDatabas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EnvironmentDatabas> EnvironmentDatabasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EnvironmentDatabas>("ContentServicesModel.FK_ApplicationEnvironments_EnvironmentDatabases", "EnvironmentDatabas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EnvironmentDatabas>("ContentServicesModel.FK_ApplicationEnvironments_EnvironmentDatabases", "EnvironmentDatabas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="Environment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Environment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Environment object.
        /// </summary>
        /// <param name="environmentCode">Initial value of the EnvironmentCode property.</param>
        /// <param name="environmentName">Initial value of the EnvironmentName property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static Environment CreateEnvironment(global::System.String environmentCode, global::System.String environmentName, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            Environment environment = new Environment();
            environment.EnvironmentCode = environmentCode;
            environment.EnvironmentName = environmentName;
            environment.CreatedDateTime = createdDateTime;
            environment.ModifiedDateTime = modifiedDateTime;
            return environment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentCode
        {
            get
            {
                return _EnvironmentCode;
            }
            set
            {
                if (_EnvironmentCode != value)
                {
                    OnEnvironmentCodeChanging(value);
                    ReportPropertyChanging("EnvironmentCode");
                    _EnvironmentCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EnvironmentCode");
                    OnEnvironmentCodeChanged();
                }
            }
        }
        private global::System.String _EnvironmentCode;
        partial void OnEnvironmentCodeChanging(global::System.String value);
        partial void OnEnvironmentCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentName
        {
            get
            {
                return _EnvironmentName;
            }
            set
            {
                OnEnvironmentNameChanging(value);
                ReportPropertyChanging("EnvironmentName");
                _EnvironmentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnvironmentName");
                OnEnvironmentNameChanged();
            }
        }
        private global::System.String _EnvironmentName;
        partial void OnEnvironmentNameChanging(global::System.String value);
        partial void OnEnvironmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_EnvironmentDatabases_Environments", "EnvironmentDatabas")]
        public EntityCollection<EnvironmentDatabas> EnvironmentDatabases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EnvironmentDatabas>("ContentServicesModel.FK_EnvironmentDatabases_Environments", "EnvironmentDatabas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EnvironmentDatabas>("ContentServicesModel.FK_EnvironmentDatabases_Environments", "EnvironmentDatabas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="EnvironmentDatabas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnvironmentDatabas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EnvironmentDatabas object.
        /// </summary>
        /// <param name="environmentCode">Initial value of the EnvironmentCode property.</param>
        /// <param name="databaseCode">Initial value of the DatabaseCode property.</param>
        /// <param name="connectionString">Initial value of the ConnectionString property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static EnvironmentDatabas CreateEnvironmentDatabas(global::System.String environmentCode, global::System.String databaseCode, global::System.String connectionString, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            EnvironmentDatabas environmentDatabas = new EnvironmentDatabas();
            environmentDatabas.EnvironmentCode = environmentCode;
            environmentDatabas.DatabaseCode = databaseCode;
            environmentDatabas.ConnectionString = connectionString;
            environmentDatabas.CreatedDateTime = createdDateTime;
            environmentDatabas.ModifiedDateTime = modifiedDateTime;
            return environmentDatabas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentCode
        {
            get
            {
                return _EnvironmentCode;
            }
            set
            {
                if (_EnvironmentCode != value)
                {
                    OnEnvironmentCodeChanging(value);
                    ReportPropertyChanging("EnvironmentCode");
                    _EnvironmentCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EnvironmentCode");
                    OnEnvironmentCodeChanged();
                }
            }
        }
        private global::System.String _EnvironmentCode;
        partial void OnEnvironmentCodeChanging(global::System.String value);
        partial void OnEnvironmentCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DatabaseCode
        {
            get
            {
                return _DatabaseCode;
            }
            set
            {
                if (_DatabaseCode != value)
                {
                    OnDatabaseCodeChanging(value);
                    ReportPropertyChanging("DatabaseCode");
                    _DatabaseCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DatabaseCode");
                    OnDatabaseCodeChanged();
                }
            }
        }
        private global::System.String _DatabaseCode;
        partial void OnDatabaseCodeChanging(global::System.String value);
        partial void OnDatabaseCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectionString
        {
            get
            {
                return _ConnectionString;
            }
            set
            {
                OnConnectionStringChanging(value);
                ReportPropertyChanging("ConnectionString");
                _ConnectionString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectionString");
                OnConnectionStringChanged();
            }
        }
        private global::System.String _ConnectionString;
        partial void OnConnectionStringChanging(global::System.String value);
        partial void OnConnectionStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_ApplicationEnvironments_EnvironmentDatabases", "ApplicationEnvironment")]
        public EntityCollection<ApplicationEnvironment> ApplicationEnvironments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApplicationEnvironment>("ContentServicesModel.FK_ApplicationEnvironments_EnvironmentDatabases", "ApplicationEnvironment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApplicationEnvironment>("ContentServicesModel.FK_ApplicationEnvironments_EnvironmentDatabases", "ApplicationEnvironment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_EnvironmentDatabases_Environments", "Environment")]
        public Environment Environment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("ContentServicesModel.FK_EnvironmentDatabases_Environments", "Environment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("ContentServicesModel.FK_EnvironmentDatabases_Environments", "Environment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Environment> EnvironmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Environment>("ContentServicesModel.FK_EnvironmentDatabases_Environments", "Environment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Environment>("ContentServicesModel.FK_EnvironmentDatabases_Environments", "Environment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="FilterCriterion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FilterCriterion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FilterCriterion object.
        /// </summary>
        /// <param name="applicationCode">Initial value of the ApplicationCode property.</param>
        /// <param name="filterCode">Initial value of the FilterCode property.</param>
        /// <param name="criterionCode">Initial value of the CriterionCode property.</param>
        /// <param name="criterionOrder">Initial value of the CriterionOrder property.</param>
        /// <param name="criterionName">Initial value of the CriterionName property.</param>
        /// <param name="criterionType">Initial value of the CriterionType property.</param>
        /// <param name="isRequired">Initial value of the IsRequired property.</param>
        /// <param name="isIncludedByDefault">Initial value of the IsIncludedByDefault property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static FilterCriterion CreateFilterCriterion(global::System.String applicationCode, global::System.String filterCode, global::System.String criterionCode, global::System.Int32 criterionOrder, global::System.String criterionName, global::System.String criterionType, global::System.String isRequired, global::System.String isIncludedByDefault, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            FilterCriterion filterCriterion = new FilterCriterion();
            filterCriterion.ApplicationCode = applicationCode;
            filterCriterion.FilterCode = filterCode;
            filterCriterion.CriterionCode = criterionCode;
            filterCriterion.CriterionOrder = criterionOrder;
            filterCriterion.CriterionName = criterionName;
            filterCriterion.CriterionType = criterionType;
            filterCriterion.IsRequired = isRequired;
            filterCriterion.IsIncludedByDefault = isIncludedByDefault;
            filterCriterion.CreatedDateTime = createdDateTime;
            filterCriterion.ModifiedDateTime = modifiedDateTime;
            return filterCriterion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationCode
        {
            get
            {
                return _ApplicationCode;
            }
            set
            {
                if (_ApplicationCode != value)
                {
                    OnApplicationCodeChanging(value);
                    ReportPropertyChanging("ApplicationCode");
                    _ApplicationCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ApplicationCode");
                    OnApplicationCodeChanged();
                }
            }
        }
        private global::System.String _ApplicationCode;
        partial void OnApplicationCodeChanging(global::System.String value);
        partial void OnApplicationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FilterCode
        {
            get
            {
                return _FilterCode;
            }
            set
            {
                if (_FilterCode != value)
                {
                    OnFilterCodeChanging(value);
                    ReportPropertyChanging("FilterCode");
                    _FilterCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FilterCode");
                    OnFilterCodeChanged();
                }
            }
        }
        private global::System.String _FilterCode;
        partial void OnFilterCodeChanging(global::System.String value);
        partial void OnFilterCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CriterionCode
        {
            get
            {
                return _CriterionCode;
            }
            set
            {
                if (_CriterionCode != value)
                {
                    OnCriterionCodeChanging(value);
                    ReportPropertyChanging("CriterionCode");
                    _CriterionCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CriterionCode");
                    OnCriterionCodeChanged();
                }
            }
        }
        private global::System.String _CriterionCode;
        partial void OnCriterionCodeChanging(global::System.String value);
        partial void OnCriterionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CriterionOrder
        {
            get
            {
                return _CriterionOrder;
            }
            set
            {
                OnCriterionOrderChanging(value);
                ReportPropertyChanging("CriterionOrder");
                _CriterionOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CriterionOrder");
                OnCriterionOrderChanged();
            }
        }
        private global::System.Int32 _CriterionOrder;
        partial void OnCriterionOrderChanging(global::System.Int32 value);
        partial void OnCriterionOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CriterionName
        {
            get
            {
                return _CriterionName;
            }
            set
            {
                OnCriterionNameChanging(value);
                ReportPropertyChanging("CriterionName");
                _CriterionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CriterionName");
                OnCriterionNameChanged();
            }
        }
        private global::System.String _CriterionName;
        partial void OnCriterionNameChanging(global::System.String value);
        partial void OnCriterionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CriterionType
        {
            get
            {
                return _CriterionType;
            }
            set
            {
                OnCriterionTypeChanging(value);
                ReportPropertyChanging("CriterionType");
                _CriterionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CriterionType");
                OnCriterionTypeChanged();
            }
        }
        private global::System.String _CriterionType;
        partial void OnCriterionTypeChanging(global::System.String value);
        partial void OnCriterionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FilterGroupCode
        {
            get
            {
                return _FilterGroupCode;
            }
            set
            {
                OnFilterGroupCodeChanging(value);
                ReportPropertyChanging("FilterGroupCode");
                _FilterGroupCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FilterGroupCode");
                OnFilterGroupCodeChanged();
            }
        }
        private global::System.String _FilterGroupCode;
        partial void OnFilterGroupCodeChanging(global::System.String value);
        partial void OnFilterGroupCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsRequired
        {
            get
            {
                return _IsRequired;
            }
            set
            {
                OnIsRequiredChanging(value);
                ReportPropertyChanging("IsRequired");
                _IsRequired = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsRequired");
                OnIsRequiredChanged();
            }
        }
        private global::System.String _IsRequired;
        partial void OnIsRequiredChanging(global::System.String value);
        partial void OnIsRequiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ListKeyType
        {
            get
            {
                return _ListKeyType;
            }
            set
            {
                OnListKeyTypeChanging(value);
                ReportPropertyChanging("ListKeyType");
                _ListKeyType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ListKeyType");
                OnListKeyTypeChanged();
            }
        }
        private global::System.String _ListKeyType;
        partial void OnListKeyTypeChanging(global::System.String value);
        partial void OnListKeyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DbColumnName
        {
            get
            {
                return _DbColumnName;
            }
            set
            {
                OnDbColumnNameChanging(value);
                ReportPropertyChanging("DbColumnName");
                _DbColumnName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DbColumnName");
                OnDbColumnNameChanged();
            }
        }
        private global::System.String _DbColumnName;
        partial void OnDbColumnNameChanging(global::System.String value);
        partial void OnDbColumnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayNote
        {
            get
            {
                return _DisplayNote;
            }
            set
            {
                OnDisplayNoteChanging(value);
                ReportPropertyChanging("DisplayNote");
                _DisplayNote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayNote");
                OnDisplayNoteChanged();
            }
        }
        private global::System.String _DisplayNote;
        partial void OnDisplayNoteChanging(global::System.String value);
        partial void OnDisplayNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsIncludedByDefault
        {
            get
            {
                return _IsIncludedByDefault;
            }
            set
            {
                OnIsIncludedByDefaultChanging(value);
                ReportPropertyChanging("IsIncludedByDefault");
                _IsIncludedByDefault = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsIncludedByDefault");
                OnIsIncludedByDefaultChanged();
            }
        }
        private global::System.String _IsIncludedByDefault;
        partial void OnIsIncludedByDefaultChanging(global::System.String value);
        partial void OnIsIncludedByDefaultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_FilterCriterionDate_FilterCriterion", "FilterCriterionDate")]
        public FilterCriterionDate FilterCriterionDate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FilterCriterionDate>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterionDate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FilterCriterionDate>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterionDate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FilterCriterionDate> FilterCriterionDateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FilterCriterionDate>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterionDate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FilterCriterionDate>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterionDate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="FilterCriterionDate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FilterCriterionDate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FilterCriterionDate object.
        /// </summary>
        /// <param name="applicationCode">Initial value of the ApplicationCode property.</param>
        /// <param name="filterCode">Initial value of the FilterCode property.</param>
        /// <param name="criterionCode">Initial value of the CriterionCode property.</param>
        /// <param name="allowDateInPast">Initial value of the AllowDateInPast property.</param>
        /// <param name="allowDateInFuture">Initial value of the AllowDateInFuture property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static FilterCriterionDate CreateFilterCriterionDate(global::System.String applicationCode, global::System.String filterCode, global::System.String criterionCode, global::System.String allowDateInPast, global::System.String allowDateInFuture, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            FilterCriterionDate filterCriterionDate = new FilterCriterionDate();
            filterCriterionDate.ApplicationCode = applicationCode;
            filterCriterionDate.FilterCode = filterCode;
            filterCriterionDate.CriterionCode = criterionCode;
            filterCriterionDate.AllowDateInPast = allowDateInPast;
            filterCriterionDate.AllowDateInFuture = allowDateInFuture;
            filterCriterionDate.CreatedDateTime = createdDateTime;
            filterCriterionDate.ModifiedDateTime = modifiedDateTime;
            return filterCriterionDate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationCode
        {
            get
            {
                return _ApplicationCode;
            }
            set
            {
                if (_ApplicationCode != value)
                {
                    OnApplicationCodeChanging(value);
                    ReportPropertyChanging("ApplicationCode");
                    _ApplicationCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ApplicationCode");
                    OnApplicationCodeChanged();
                }
            }
        }
        private global::System.String _ApplicationCode;
        partial void OnApplicationCodeChanging(global::System.String value);
        partial void OnApplicationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FilterCode
        {
            get
            {
                return _FilterCode;
            }
            set
            {
                if (_FilterCode != value)
                {
                    OnFilterCodeChanging(value);
                    ReportPropertyChanging("FilterCode");
                    _FilterCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FilterCode");
                    OnFilterCodeChanged();
                }
            }
        }
        private global::System.String _FilterCode;
        partial void OnFilterCodeChanging(global::System.String value);
        partial void OnFilterCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CriterionCode
        {
            get
            {
                return _CriterionCode;
            }
            set
            {
                if (_CriterionCode != value)
                {
                    OnCriterionCodeChanging(value);
                    ReportPropertyChanging("CriterionCode");
                    _CriterionCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CriterionCode");
                    OnCriterionCodeChanged();
                }
            }
        }
        private global::System.String _CriterionCode;
        partial void OnCriterionCodeChanging(global::System.String value);
        partial void OnCriterionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AllowDateInPast
        {
            get
            {
                return _AllowDateInPast;
            }
            set
            {
                OnAllowDateInPastChanging(value);
                ReportPropertyChanging("AllowDateInPast");
                _AllowDateInPast = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AllowDateInPast");
                OnAllowDateInPastChanged();
            }
        }
        private global::System.String _AllowDateInPast;
        partial void OnAllowDateInPastChanging(global::System.String value);
        partial void OnAllowDateInPastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AllowDateInFuture
        {
            get
            {
                return _AllowDateInFuture;
            }
            set
            {
                OnAllowDateInFutureChanging(value);
                ReportPropertyChanging("AllowDateInFuture");
                _AllowDateInFuture = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AllowDateInFuture");
                OnAllowDateInFutureChanged();
            }
        }
        private global::System.String _AllowDateInFuture;
        partial void OnAllowDateInFutureChanging(global::System.String value);
        partial void OnAllowDateInFutureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServicesModel", "FK_FilterCriterionDate_FilterCriterion", "FilterCriterion")]
        public FilterCriterion FilterCriterion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FilterCriterion>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FilterCriterion>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterion").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FilterCriterion> FilterCriterionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FilterCriterion>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FilterCriterion>("ContentServicesModel.FK_FilterCriterionDate_FilterCriterion", "FilterCriterion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServicesModel", Name="ReportPlan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReportPlan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReportPlan object.
        /// </summary>
        /// <param name="planId">Initial value of the PlanId property.</param>
        /// <param name="applicationCode">Initial value of the ApplicationCode property.</param>
        /// <param name="filterCode">Initial value of the FilterCode property.</param>
        /// <param name="criteria">Initial value of the Criteria property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        public static ReportPlan CreateReportPlan(global::System.Int32 planId, global::System.String applicationCode, global::System.String filterCode, global::System.String criteria, global::System.DateTime createdDateTime, global::System.Guid createdByGuid)
        {
            ReportPlan reportPlan = new ReportPlan();
            reportPlan.PlanId = planId;
            reportPlan.ApplicationCode = applicationCode;
            reportPlan.FilterCode = filterCode;
            reportPlan.Criteria = criteria;
            reportPlan.CreatedDateTime = createdDateTime;
            reportPlan.CreatedByGuid = createdByGuid;
            return reportPlan;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlanId
        {
            get
            {
                return _PlanId;
            }
            set
            {
                if (_PlanId != value)
                {
                    OnPlanIdChanging(value);
                    ReportPropertyChanging("PlanId");
                    _PlanId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlanId");
                    OnPlanIdChanged();
                }
            }
        }
        private global::System.Int32 _PlanId;
        partial void OnPlanIdChanging(global::System.Int32 value);
        partial void OnPlanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationCode
        {
            get
            {
                return _ApplicationCode;
            }
            set
            {
                OnApplicationCodeChanging(value);
                ReportPropertyChanging("ApplicationCode");
                _ApplicationCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApplicationCode");
                OnApplicationCodeChanged();
            }
        }
        private global::System.String _ApplicationCode;
        partial void OnApplicationCodeChanging(global::System.String value);
        partial void OnApplicationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReportCode
        {
            get
            {
                return _ReportCode;
            }
            set
            {
                OnReportCodeChanging(value);
                ReportPropertyChanging("ReportCode");
                _ReportCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReportCode");
                OnReportCodeChanged();
            }
        }
        private global::System.String _ReportCode;
        partial void OnReportCodeChanging(global::System.String value);
        partial void OnReportCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FilterCode
        {
            get
            {
                return _FilterCode;
            }
            set
            {
                OnFilterCodeChanging(value);
                ReportPropertyChanging("FilterCode");
                _FilterCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FilterCode");
                OnFilterCodeChanged();
            }
        }
        private global::System.String _FilterCode;
        partial void OnFilterCodeChanging(global::System.String value);
        partial void OnFilterCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentCode
        {
            get
            {
                return _EnvironmentCode;
            }
            set
            {
                OnEnvironmentCodeChanging(value);
                ReportPropertyChanging("EnvironmentCode");
                _EnvironmentCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EnvironmentCode");
                OnEnvironmentCodeChanged();
            }
        }
        private global::System.String _EnvironmentCode;
        partial void OnEnvironmentCodeChanging(global::System.String value);
        partial void OnEnvironmentCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Criteria
        {
            get
            {
                return _Criteria;
            }
            set
            {
                OnCriteriaChanging(value);
                ReportPropertyChanging("Criteria");
                _Criteria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Criteria");
                OnCriteriaChanged();
            }
        }
        private global::System.String _Criteria;
        partial void OnCriteriaChanging(global::System.String value);
        partial void OnCriteriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();

        #endregion

    
    }

    #endregion

    
}
