// Copyright [2015] [Centers for Disease Control and Prevention] 
// Licensed under the CDC Custom Open Source License 1 (the 'License'); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at
// 
//   http://t.cdc.gov/O4O
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ContentServices_ECardsDbModel", "FK_CardInstances_CardMessages", "CardMessage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.CdcECardProvider.Model.CardMessage), "CardInstance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.CdcECardProvider.Model.CardInstance), true)]

#endregion

namespace Gov.Hhs.Cdc.CdcECardProvider.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ECardDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ECardDbEntities object using the connection string found in the 'ECardDbEntities' section of the application configuration file.
        /// </summary>
        public ECardDbEntities() : base("name=ECardDbEntities", "ECardDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ECardDbEntities object.
        /// </summary>
        public ECardDbEntities(string connectionString) : base(connectionString, "ECardDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ECardDbEntities object.
        /// </summary>
        public ECardDbEntities(EntityConnection connection) : base(connection, "ECardDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardInstance> CardInstances
        {
            get
            {
                if ((_CardInstances == null))
                {
                    _CardInstances = base.CreateObjectSet<CardInstance>("CardInstances");
                }
                return _CardInstances;
            }
        }
        private ObjectSet<CardInstance> _CardInstances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardMessage> CardMessages
        {
            get
            {
                if ((_CardMessages == null))
                {
                    _CardMessages = base.CreateObjectSet<CardMessage>("CardMessages");
                }
                return _CardMessages;
            }
        }
        private ObjectSet<CardMessage> _CardMessages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardInstances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardInstances(CardInstance cardInstance)
        {
            base.AddObject("CardInstances", cardInstance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardMessages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardMessages(CardMessage cardMessage)
        {
            base.AddObject("CardMessages", cardMessage);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="p_CardInstanceId">No Metadata Documentation available.</param>
        /// <param name="p_ModifiedByGuid">No Metadata Documentation available.</param>
        public int UpdateCardViewedCount(Nullable<global::System.Guid> p_CardInstanceId, Nullable<global::System.Guid> p_ModifiedByGuid)
        {
            ObjectParameter p_CardInstanceIdParameter;
            if (p_CardInstanceId.HasValue)
            {
                p_CardInstanceIdParameter = new ObjectParameter("p_CardInstanceId", p_CardInstanceId);
            }
            else
            {
                p_CardInstanceIdParameter = new ObjectParameter("p_CardInstanceId", typeof(global::System.Guid));
            }
    
            ObjectParameter p_ModifiedByGuidParameter;
            if (p_ModifiedByGuid.HasValue)
            {
                p_ModifiedByGuidParameter = new ObjectParameter("p_ModifiedByGuid", p_ModifiedByGuid);
            }
            else
            {
                p_ModifiedByGuidParameter = new ObjectParameter("p_ModifiedByGuid", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction("UpdateCardViewedCount", p_CardInstanceIdParameter, p_ModifiedByGuidParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_ECardsDbModel", Name="CardInstance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardInstance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardInstance object.
        /// </summary>
        /// <param name="cardInstanceId">Initial value of the CardInstanceId property.</param>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="cardMessageId">Initial value of the CardMessageId property.</param>
        /// <param name="isSender">Initial value of the IsSender property.</param>
        /// <param name="viewCount">Initial value of the ViewCount property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static CardInstance CreateCardInstance(global::System.Guid cardInstanceId, global::System.Int32 mediaId, global::System.Int32 cardMessageId, global::System.String isSender, global::System.Int32 viewCount, global::System.String active, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime)
        {
            CardInstance cardInstance = new CardInstance();
            cardInstance.CardInstanceId = cardInstanceId;
            cardInstance.MediaId = mediaId;
            cardInstance.CardMessageId = cardMessageId;
            cardInstance.IsSender = isSender;
            cardInstance.ViewCount = viewCount;
            cardInstance.Active = active;
            cardInstance.CreatedByGuid = createdByGuid;
            cardInstance.CreatedDateTime = createdDateTime;
            cardInstance.ModifiedByGuid = modifiedByGuid;
            cardInstance.ModifiedDateTime = modifiedDateTime;
            return cardInstance;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CardInstanceId
        {
            get
            {
                return _CardInstanceId;
            }
            set
            {
                if (_CardInstanceId != value)
                {
                    OnCardInstanceIdChanging(value);
                    ReportPropertyChanging("CardInstanceId");
                    _CardInstanceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardInstanceId");
                    OnCardInstanceIdChanged();
                }
            }
        }
        private global::System.Guid _CardInstanceId;
        partial void OnCardInstanceIdChanging(global::System.Guid value);
        partial void OnCardInstanceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaId
        {
            get
            {
                return _MediaId;
            }
            set
            {
                OnMediaIdChanging(value);
                ReportPropertyChanging("MediaId");
                _MediaId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MediaId");
                OnMediaIdChanged();
            }
        }
        private global::System.Int32 _MediaId;
        partial void OnMediaIdChanging(global::System.Int32 value);
        partial void OnMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardMessageId
        {
            get
            {
                return _CardMessageId;
            }
            set
            {
                OnCardMessageIdChanging(value);
                ReportPropertyChanging("CardMessageId");
                _CardMessageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardMessageId");
                OnCardMessageIdChanged();
            }
        }
        private global::System.Int32 _CardMessageId;
        partial void OnCardMessageIdChanging(global::System.Int32 value);
        partial void OnCardMessageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsSender
        {
            get
            {
                return _IsSender;
            }
            set
            {
                OnIsSenderChanging(value);
                ReportPropertyChanging("IsSender");
                _IsSender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IsSender");
                OnIsSenderChanged();
            }
        }
        private global::System.String _IsSender;
        partial void OnIsSenderChanging(global::System.String value);
        partial void OnIsSenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ViewCount
        {
            get
            {
                return _ViewCount;
            }
            set
            {
                OnViewCountChanging(value);
                ReportPropertyChanging("ViewCount");
                _ViewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ViewCount");
                OnViewCountChanged();
            }
        }
        private global::System.Int32 _ViewCount;
        partial void OnViewCountChanging(global::System.Int32 value);
        partial void OnViewCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastViewedDateTime
        {
            get
            {
                return _LastViewedDateTime;
            }
            set
            {
                OnLastViewedDateTimeChanging(value);
                ReportPropertyChanging("LastViewedDateTime");
                _LastViewedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastViewedDateTime");
                OnLastViewedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastViewedDateTime;
        partial void OnLastViewedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastViewedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.String _Active;
        partial void OnActiveChanging(global::System.String value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_ECardsDbModel", "FK_CardInstances_CardMessages", "CardMessage")]
        public CardMessage CardMessage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardMessage>("ContentServices_ECardsDbModel.FK_CardInstances_CardMessages", "CardMessage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardMessage>("ContentServices_ECardsDbModel.FK_CardInstances_CardMessages", "CardMessage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CardMessage> CardMessageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardMessage>("ContentServices_ECardsDbModel.FK_CardInstances_CardMessages", "CardMessage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CardMessage>("ContentServices_ECardsDbModel.FK_CardInstances_CardMessages", "CardMessage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_ECardsDbModel", Name="CardMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardMessage object.
        /// </summary>
        /// <param name="cardMessageId">Initial value of the CardMessageId property.</param>
        /// <param name="personalMessage">Initial value of the PersonalMessage property.</param>
        /// <param name="fromMobile">Initial value of the FromMobile property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static CardMessage CreateCardMessage(global::System.Int32 cardMessageId, global::System.String personalMessage, global::System.String fromMobile, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime)
        {
            CardMessage cardMessage = new CardMessage();
            cardMessage.CardMessageId = cardMessageId;
            cardMessage.PersonalMessage = personalMessage;
            cardMessage.FromMobile = fromMobile;
            cardMessage.CreatedByGuid = createdByGuid;
            cardMessage.CreatedDateTime = createdDateTime;
            cardMessage.ModifiedByGuid = modifiedByGuid;
            cardMessage.ModifiedDateTime = modifiedDateTime;
            return cardMessage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardMessageId
        {
            get
            {
                return _CardMessageId;
            }
            set
            {
                if (_CardMessageId != value)
                {
                    OnCardMessageIdChanging(value);
                    ReportPropertyChanging("CardMessageId");
                    _CardMessageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardMessageId");
                    OnCardMessageIdChanged();
                }
            }
        }
        private global::System.Int32 _CardMessageId;
        partial void OnCardMessageIdChanging(global::System.Int32 value);
        partial void OnCardMessageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PersonalMessage
        {
            get
            {
                return _PersonalMessage;
            }
            set
            {
                OnPersonalMessageChanging(value);
                ReportPropertyChanging("PersonalMessage");
                _PersonalMessage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PersonalMessage");
                OnPersonalMessageChanged();
            }
        }
        private global::System.String _PersonalMessage;
        partial void OnPersonalMessageChanging(global::System.String value);
        partial void OnPersonalMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StyleSheet
        {
            get
            {
                return _StyleSheet;
            }
            set
            {
                OnStyleSheetChanging(value);
                ReportPropertyChanging("StyleSheet");
                _StyleSheet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StyleSheet");
                OnStyleSheetChanged();
            }
        }
        private global::System.String _StyleSheet;
        partial void OnStyleSheetChanging(global::System.String value);
        partial void OnStyleSheetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SenderUserAgent
        {
            get
            {
                return _SenderUserAgent;
            }
            set
            {
                OnSenderUserAgentChanging(value);
                ReportPropertyChanging("SenderUserAgent");
                _SenderUserAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SenderUserAgent");
                OnSenderUserAgentChanged();
            }
        }
        private global::System.String _SenderUserAgent;
        partial void OnSenderUserAgentChanging(global::System.String value);
        partial void OnSenderUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromMobile
        {
            get
            {
                return _FromMobile;
            }
            set
            {
                OnFromMobileChanging(value);
                ReportPropertyChanging("FromMobile");
                _FromMobile = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromMobile");
                OnFromMobileChanged();
            }
        }
        private global::System.String _FromMobile;
        partial void OnFromMobileChanging(global::System.String value);
        partial void OnFromMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_ECardsDbModel", "FK_CardInstances_CardMessages", "CardInstance")]
        public EntityCollection<CardInstance> CardInstances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CardInstance>("ContentServices_ECardsDbModel.FK_CardInstances_CardMessages", "CardInstance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CardInstance>("ContentServices_ECardsDbModel.FK_CardInstances_CardMessages", "CardInstance", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
