// Copyright [2015] [Centers for Disease Control and Prevention] 
// Licensed under the CDC Custom Open Source License 1 (the 'License'); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at
// 
//   http://t.cdc.gov/O4O
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Gov.Hhs.Cdc.TransactionLogProvider
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TransactionLogDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TransactionLogDbEntities object using the connection string found in the 'TransactionLogDbEntities' section of the application configuration file.
        /// </summary>
        public TransactionLogDbEntities() : base("name=TransactionLogDbEntities", "TransactionLogDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TransactionLogDbEntities object.
        /// </summary>
        public TransactionLogDbEntities(string connectionString) : base(connectionString, "TransactionLogDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TransactionLogDbEntities object.
        /// </summary>
        public TransactionLogDbEntities(EntityConnection connection) : base(connection, "TransactionLogDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TransactionEntry> TransactionEntries
        {
            get
            {
                if ((_TransactionEntries == null))
                {
                    _TransactionEntries = base.CreateObjectSet<TransactionEntry>("TransactionEntries");
                }
                return _TransactionEntries;
            }
        }
        private ObjectSet<TransactionEntry> _TransactionEntries;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TransactionEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactionEntries(TransactionEntry transactionEntry)
        {
            base.AddObject("TransactionEntries", transactionEntry);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_SourceForgeModel", Name="TransactionEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TransactionEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TransactionEntry object.
        /// </summary>
        /// <param name="transactionId">Initial value of the TransactionId property.</param>
        /// <param name="httpMethod">Initial value of the HttpMethod property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        public static TransactionEntry CreateTransactionEntry(global::System.Int32 transactionId, global::System.String httpMethod, global::System.DateTime createdDateTime)
        {
            TransactionEntry transactionEntry = new TransactionEntry();
            transactionEntry.TransactionId = transactionId;
            transactionEntry.HttpMethod = httpMethod;
            transactionEntry.CreatedDateTime = createdDateTime;
            return transactionEntry;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionId
        {
            get
            {
                return _TransactionId;
            }
            set
            {
                if (_TransactionId != value)
                {
                    OnTransactionIdChanging(value);
                    ReportPropertyChanging("TransactionId");
                    _TransactionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransactionId");
                    OnTransactionIdChanged();
                }
            }
        }
        private global::System.Int32 _TransactionId;
        partial void OnTransactionIdChanging(global::System.Int32 value);
        partial void OnTransactionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HttpMethod
        {
            get
            {
                return _HttpMethod;
            }
            set
            {
                OnHttpMethodChanging(value);
                ReportPropertyChanging("HttpMethod");
                _HttpMethod = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HttpMethod");
                OnHttpMethodChanged();
            }
        }
        private global::System.String _HttpMethod;
        partial void OnHttpMethodChanging(global::System.String value);
        partial void OnHttpMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Resource
        {
            get
            {
                return _Resource;
            }
            set
            {
                OnResourceChanging(value);
                ReportPropertyChanging("Resource");
                _Resource = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Resource");
                OnResourceChanged();
            }
        }
        private global::System.String _Resource;
        partial void OnResourceChanging(global::System.String value);
        partial void OnResourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResourceId
        {
            get
            {
                return _ResourceId;
            }
            set
            {
                OnResourceIdChanging(value);
                ReportPropertyChanging("ResourceId");
                _ResourceId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResourceId");
                OnResourceIdChanged();
            }
        }
        private global::System.String _ResourceId;
        partial void OnResourceIdChanging(global::System.String value);
        partial void OnResourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResourceAction
        {
            get
            {
                return _ResourceAction;
            }
            set
            {
                OnResourceActionChanging(value);
                ReportPropertyChanging("ResourceAction");
                _ResourceAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResourceAction");
                OnResourceActionChanged();
            }
        }
        private global::System.String _ResourceAction;
        partial void OnResourceActionChanging(global::System.String value);
        partial void OnResourceActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QueryString
        {
            get
            {
                return _QueryString;
            }
            set
            {
                OnQueryStringChanging(value);
                ReportPropertyChanging("QueryString");
                _QueryString = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QueryString");
                OnQueryStringChanged();
            }
        }
        private global::System.String _QueryString;
        partial void OnQueryStringChanging(global::System.String value);
        partial void OnQueryStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServicePath
        {
            get
            {
                return _ServicePath;
            }
            set
            {
                OnServicePathChanging(value);
                ReportPropertyChanging("ServicePath");
                _ServicePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServicePath");
                OnServicePathChanged();
            }
        }
        private global::System.String _ServicePath;
        partial void OnServicePathChanging(global::System.String value);
        partial void OnServicePathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InputData
        {
            get
            {
                return _InputData;
            }
            set
            {
                OnInputDataChanging(value);
                ReportPropertyChanging("InputData");
                _InputData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InputData");
                OnInputDataChanged();
            }
        }
        private global::System.String _InputData;
        partial void OnInputDataChanging(global::System.String value);
        partial void OnInputDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OutputData
        {
            get
            {
                return _OutputData;
            }
            set
            {
                OnOutputDataChanging(value);
                ReportPropertyChanging("OutputData");
                _OutputData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OutputData");
                OnOutputDataChanged();
            }
        }
        private global::System.String _OutputData;
        partial void OnOutputDataChanging(global::System.String value);
        partial void OnOutputDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Messages
        {
            get
            {
                return _Messages;
            }
            set
            {
                OnMessagesChanging(value);
                ReportPropertyChanging("Messages");
                _Messages = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Messages");
                OnMessagesChanged();
            }
        }
        private global::System.String _Messages;
        partial void OnMessagesChanging(global::System.String value);
        partial void OnMessagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
