// Copyright [2015] [Centers for Disease Control and Prevention] 
// Licensed under the CDC Custom Open Source License 1 (the 'License'); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at
// 
//   http://t.cdc.gov/O4O
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ContentServices_SourceForgeModel", "FK_MediaStorage_Storage", "Storage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.Storage.Model.Storage), "MediaStorage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.Storage.Model.MediaStorage), true)]
[assembly: EdmRelationshipAttribute("ContentServices_SourceForgeModel", "FK_MediaStorage_Media", "Media", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gov.Hhs.Cdc.Storage.Model.Medias), "MediaStorage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gov.Hhs.Cdc.Storage.Model.MediaStorage), true)]

#endregion

namespace Gov.Hhs.Cdc.Storage.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StorageDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ContentServices_SourceForgeEntities object using the connection string found in the 'ContentServices_SourceForgeEntities' section of the application configuration file.
        /// </summary>
        public StorageDbEntities() : base("name=ContentServices_SourceForgeEntities", "ContentServices_SourceForgeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContentServices_SourceForgeEntities object.
        /// </summary>
        public StorageDbEntities(string connectionString) : base(connectionString, "ContentServices_SourceForgeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ContentServices_SourceForgeEntities object.
        /// </summary>
        public StorageDbEntities(EntityConnection connection) : base(connection, "ContentServices_SourceForgeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Storage> Storages
        {
            get
            {
                if ((_Storages == null))
                {
                    _Storages = base.CreateObjectSet<Storage>("Storages");
                }
                return _Storages;
            }
        }
        private ObjectSet<Storage> _Storages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Medias> Medias
        {
            get
            {
                if ((_Medias == null))
                {
                    _Medias = base.CreateObjectSet<Medias>("Medias");
                }
                return _Medias;
            }
        }
        private ObjectSet<Medias> _Medias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MediaStorage> MediaStorages
        {
            get
            {
                if ((_MediaStorages == null))
                {
                    _MediaStorages = base.CreateObjectSet<MediaStorage>("MediaStorages");
                }
                return _MediaStorages;
            }
        }
        private ObjectSet<MediaStorage> _MediaStorages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Storages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStorages(Storage storage)
        {
            base.AddObject("Storages", storage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Medias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedias(Medias medias)
        {
            base.AddObject("Medias", medias);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MediaStorages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMediaStorages(MediaStorage mediaStorage)
        {
            base.AddObject("MediaStorages", mediaStorage);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_SourceForgeModel", Name="Medias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medias : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Medias object.
        /// </summary>
        /// <param name="mediaId">Initial value of the MediaId property.</param>
        /// <param name="mediaGuid">Initial value of the MediaGuid property.</param>
        /// <param name="sourceCode">Initial value of the SourceCode property.</param>
        /// <param name="languageCode">Initial value of the LanguageCode property.</param>
        /// <param name="mediaTypeCode">Initial value of the MediaTypeCode property.</param>
        /// <param name="characterEncodingCode">Initial value of the CharacterEncodingCode property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="ratingMinimum">Initial value of the RatingMinimum property.</param>
        /// <param name="ratingMaximum">Initial value of the RatingMaximum property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static Medias CreateMedias(global::System.Int32 mediaId, global::System.Guid mediaGuid, global::System.String sourceCode, global::System.String languageCode, global::System.String mediaTypeCode, global::System.String characterEncodingCode, global::System.String title, global::System.Int32 ratingMinimum, global::System.Int32 ratingMaximum, global::System.Byte[] rowVersion, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime)
        {
            Medias medias = new Medias();
            medias.MediaId = mediaId;
            medias.MediaGuid = mediaGuid;
            medias.SourceCode = sourceCode;
            medias.LanguageCode = languageCode;
            medias.MediaTypeCode = mediaTypeCode;
            medias.CharacterEncodingCode = characterEncodingCode;
            medias.Title = title;
            medias.RatingMinimum = ratingMinimum;
            medias.RatingMaximum = ratingMaximum;
            medias.RowVersion = rowVersion;
            medias.CreatedByGuid = createdByGuid;
            medias.CreatedDateTime = createdDateTime;
            medias.ModifiedByGuid = modifiedByGuid;
            medias.ModifiedDateTime = modifiedDateTime;
            return medias;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaId
        {
            get
            {
                return _MediaId;
            }
            set
            {
                if (_MediaId != value)
                {
                    OnMediaIdChanging(value);
                    ReportPropertyChanging("MediaId");
                    _MediaId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaId");
                    OnMediaIdChanged();
                }
            }
        }
        private global::System.Int32 _MediaId;
        partial void OnMediaIdChanging(global::System.Int32 value);
        partial void OnMediaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MediaGuid
        {
            get
            {
                return _MediaGuid;
            }
            set
            {
                OnMediaGuidChanging(value);
                ReportPropertyChanging("MediaGuid");
                _MediaGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MediaGuid");
                OnMediaGuidChanged();
            }
        }
        private global::System.Guid _MediaGuid;
        partial void OnMediaGuidChanging(global::System.Guid value);
        partial void OnMediaGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExternalIdentifier
        {
            get
            {
                return _ExternalIdentifier;
            }
            set
            {
                OnExternalIdentifierChanging(value);
                ReportPropertyChanging("ExternalIdentifier");
                _ExternalIdentifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExternalIdentifier");
                OnExternalIdentifierChanged();
            }
        }
        private global::System.String _ExternalIdentifier;
        partial void OnExternalIdentifierChanging(global::System.String value);
        partial void OnExternalIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SourceCode
        {
            get
            {
                return _SourceCode;
            }
            set
            {
                OnSourceCodeChanging(value);
                ReportPropertyChanging("SourceCode");
                _SourceCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SourceCode");
                OnSourceCodeChanged();
            }
        }
        private global::System.String _SourceCode;
        partial void OnSourceCodeChanging(global::System.String value);
        partial void OnSourceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OwningBusinessUnitId
        {
            get
            {
                return _OwningBusinessUnitId;
            }
            set
            {
                OnOwningBusinessUnitIdChanging(value);
                ReportPropertyChanging("OwningBusinessUnitId");
                _OwningBusinessUnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwningBusinessUnitId");
                OnOwningBusinessUnitIdChanged();
            }
        }
        private Nullable<global::System.Int32> _OwningBusinessUnitId;
        partial void OnOwningBusinessUnitIdChanging(Nullable<global::System.Int32> value);
        partial void OnOwningBusinessUnitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaintainingBusinessUnitId
        {
            get
            {
                return _MaintainingBusinessUnitId;
            }
            set
            {
                OnMaintainingBusinessUnitIdChanging(value);
                ReportPropertyChanging("MaintainingBusinessUnitId");
                _MaintainingBusinessUnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaintainingBusinessUnitId");
                OnMaintainingBusinessUnitIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MaintainingBusinessUnitId;
        partial void OnMaintainingBusinessUnitIdChanging(Nullable<global::System.Int32> value);
        partial void OnMaintainingBusinessUnitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LanguageCode
        {
            get
            {
                return _LanguageCode;
            }
            set
            {
                OnLanguageCodeChanging(value);
                ReportPropertyChanging("LanguageCode");
                _LanguageCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LanguageCode");
                OnLanguageCodeChanged();
            }
        }
        private global::System.String _LanguageCode;
        partial void OnLanguageCodeChanging(global::System.String value);
        partial void OnLanguageCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MediaTypeCode
        {
            get
            {
                return _MediaTypeCode;
            }
            set
            {
                OnMediaTypeCodeChanging(value);
                ReportPropertyChanging("MediaTypeCode");
                _MediaTypeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MediaTypeCode");
                OnMediaTypeCodeChanged();
            }
        }
        private global::System.String _MediaTypeCode;
        partial void OnMediaTypeCodeChanging(global::System.String value);
        partial void OnMediaTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MimeTypeCode
        {
            get
            {
                return _MimeTypeCode;
            }
            set
            {
                OnMimeTypeCodeChanging(value);
                ReportPropertyChanging("MimeTypeCode");
                _MimeTypeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MimeTypeCode");
                OnMimeTypeCodeChanged();
            }
        }
        private global::System.String _MimeTypeCode;
        partial void OnMimeTypeCodeChanging(global::System.String value);
        partial void OnMimeTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CharacterEncodingCode
        {
            get
            {
                return _CharacterEncodingCode;
            }
            set
            {
                OnCharacterEncodingCodeChanging(value);
                ReportPropertyChanging("CharacterEncodingCode");
                _CharacterEncodingCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CharacterEncodingCode");
                OnCharacterEncodingCodeChanged();
            }
        }
        private global::System.String _CharacterEncodingCode;
        partial void OnCharacterEncodingCodeChanging(global::System.String value);
        partial void OnCharacterEncodingCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubTitle
        {
            get
            {
                return _SubTitle;
            }
            set
            {
                OnSubTitleChanging(value);
                ReportPropertyChanging("SubTitle");
                _SubTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubTitle");
                OnSubTitleChanged();
            }
        }
        private global::System.String _SubTitle;
        partial void OnSubTitleChanging(global::System.String value);
        partial void OnSubTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceUrl
        {
            get
            {
                return _SourceUrl;
            }
            set
            {
                OnSourceUrlChanging(value);
                ReportPropertyChanging("SourceUrl");
                _SourceUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceUrl");
                OnSourceUrlChanged();
            }
        }
        private global::System.String _SourceUrl;
        partial void OnSourceUrlChanging(global::System.String value);
        partial void OnSourceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TargetUrl
        {
            get
            {
                return _TargetUrl;
            }
            set
            {
                OnTargetUrlChanging(value);
                ReportPropertyChanging("TargetUrl");
                _TargetUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TargetUrl");
                OnTargetUrlChanged();
            }
        }
        private global::System.String _TargetUrl;
        partial void OnTargetUrlChanging(global::System.String value);
        partial void OnTargetUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AlternateText
        {
            get
            {
                return _AlternateText;
            }
            set
            {
                OnAlternateTextChanging(value);
                ReportPropertyChanging("AlternateText");
                _AlternateText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AlternateText");
                OnAlternateTextChanged();
            }
        }
        private global::System.String _AlternateText;
        partial void OnAlternateTextChanging(global::System.String value);
        partial void OnAlternateTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoScriptText
        {
            get
            {
                return _NoScriptText;
            }
            set
            {
                OnNoScriptTextChanging(value);
                ReportPropertyChanging("NoScriptText");
                _NoScriptText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoScriptText");
                OnNoScriptTextChanged();
            }
        }
        private global::System.String _NoScriptText;
        partial void OnNoScriptTextChanging(global::System.String value);
        partial void OnNoScriptTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FeaturedText
        {
            get
            {
                return _FeaturedText;
            }
            set
            {
                OnFeaturedTextChanging(value);
                ReportPropertyChanging("FeaturedText");
                _FeaturedText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FeaturedText");
                OnFeaturedTextChanged();
            }
        }
        private global::System.String _FeaturedText;
        partial void OnFeaturedTextChanging(global::System.String value);
        partial void OnFeaturedTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Int32> _Length;
        partial void OnLengthChanging(Nullable<global::System.Int32> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _Size;
        partial void OnSizeChanging(Nullable<global::System.Int32> value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RatingOverride
        {
            get
            {
                return _RatingOverride;
            }
            set
            {
                OnRatingOverrideChanging(value);
                ReportPropertyChanging("RatingOverride");
                _RatingOverride = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingOverride");
                OnRatingOverrideChanged();
            }
        }
        private Nullable<global::System.Int32> _RatingOverride;
        partial void OnRatingOverrideChanging(Nullable<global::System.Int32> value);
        partial void OnRatingOverrideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RatingMinimum
        {
            get
            {
                return _RatingMinimum;
            }
            set
            {
                OnRatingMinimumChanging(value);
                ReportPropertyChanging("RatingMinimum");
                _RatingMinimum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingMinimum");
                OnRatingMinimumChanged();
            }
        }
        private global::System.Int32 _RatingMinimum;
        partial void OnRatingMinimumChanging(global::System.Int32 value);
        partial void OnRatingMinimumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RatingMaximum
        {
            get
            {
                return _RatingMaximum;
            }
            set
            {
                OnRatingMaximumChanging(value);
                ReportPropertyChanging("RatingMaximum");
                _RatingMaximum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingMaximum");
                OnRatingMaximumChanged();
            }
        }
        private global::System.Int32 _RatingMaximum;
        partial void OnRatingMaximumChanging(global::System.Int32 value);
        partial void OnRatingMaximumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmbedParameters
        {
            get
            {
                return _EmbedParameters;
            }
            set
            {
                OnEmbedParametersChanging(value);
                ReportPropertyChanging("EmbedParameters");
                _EmbedParameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmbedParameters");
                OnEmbedParametersChanged();
            }
        }
        private global::System.String _EmbedParameters;
        partial void OnEmbedParametersChanging(global::System.String value);
        partial void OnEmbedParametersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastReviewedDateTime
        {
            get
            {
                return _LastReviewedDateTime;
            }
            set
            {
                OnLastReviewedDateTimeChanging(value);
                ReportPropertyChanging("LastReviewedDateTime");
                _LastReviewedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastReviewedDateTime");
                OnLastReviewedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastReviewedDateTime;
        partial void OnLastReviewedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastReviewedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PublishedDateTime
        {
            get
            {
                return _PublishedDateTime;
            }
            set
            {
                OnPublishedDateTimeChanging(value);
                ReportPropertyChanging("PublishedDateTime");
                _PublishedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishedDateTime");
                OnPublishedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PublishedDateTime;
        partial void OnPublishedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPublishedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PersistentURLToken
        {
            get
            {
                return _PersistentURLToken;
            }
            set
            {
                OnPersistentURLTokenChanging(value);
                ReportPropertyChanging("PersistentURLToken");
                _PersistentURLToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PersistentURLToken");
                OnPersistentURLTokenChanged();
            }
        }
        private global::System.String _PersistentURLToken;
        partial void OnPersistentURLTokenChanging(global::System.String value);
        partial void OnPersistentURLTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MediaStatusCode
        {
            get
            {
                return _MediaStatusCode;
            }
            set
            {
                OnMediaStatusCodeChanging(value);
                ReportPropertyChanging("MediaStatusCode");
                _MediaStatusCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MediaStatusCode");
                OnMediaStatusCodeChanged();
            }
        }
        private global::System.String _MediaStatusCode;
        partial void OnMediaStatusCodeChanging(global::System.String value);
        partial void OnMediaStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainName
        {
            get
            {
                return _DomainName;
            }
            set
            {
                OnDomainNameChanging(value);
                ReportPropertyChanging("DomainName");
                _DomainName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainName");
                OnDomainNameChanged();
            }
        }
        private global::System.String _DomainName;
        partial void OnDomainNameChanging(global::System.String value);
        partial void OnDomainNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentAuthored
        {
            get
            {
                return _DateContentAuthored;
            }
            set
            {
                OnDateContentAuthoredChanging(value);
                ReportPropertyChanging("DateContentAuthored");
                _DateContentAuthored = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentAuthored");
                OnDateContentAuthoredChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentAuthored;
        partial void OnDateContentAuthoredChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentAuthoredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentUpdated
        {
            get
            {
                return _DateContentUpdated;
            }
            set
            {
                OnDateContentUpdatedChanging(value);
                ReportPropertyChanging("DateContentUpdated");
                _DateContentUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentUpdated");
                OnDateContentUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentUpdated;
        partial void OnDateContentUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentPublished
        {
            get
            {
                return _DateContentPublished;
            }
            set
            {
                OnDateContentPublishedChanging(value);
                ReportPropertyChanging("DateContentPublished");
                _DateContentPublished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentPublished");
                OnDateContentPublishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentPublished;
        partial void OnDateContentPublishedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentPublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateContentReviewed
        {
            get
            {
                return _DateContentReviewed;
            }
            set
            {
                OnDateContentReviewedChanging(value);
                ReportPropertyChanging("DateContentReviewed");
                _DateContentReviewed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateContentReviewed");
                OnDateContentReviewedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateContentReviewed;
        partial void OnDateContentReviewedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateContentReviewedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSyndicationCaptured
        {
            get
            {
                return _DateSyndicationCaptured;
            }
            set
            {
                OnDateSyndicationCapturedChanging(value);
                ReportPropertyChanging("DateSyndicationCaptured");
                _DateSyndicationCaptured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSyndicationCaptured");
                OnDateSyndicationCapturedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSyndicationCaptured;
        partial void OnDateSyndicationCapturedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSyndicationCapturedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSyndicationUpdated
        {
            get
            {
                return _DateSyndicationUpdated;
            }
            set
            {
                OnDateSyndicationUpdatedChanging(value);
                ReportPropertyChanging("DateSyndicationUpdated");
                _DateSyndicationUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSyndicationUpdated");
                OnDateSyndicationUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSyndicationUpdated;
        partial void OnDateSyndicationUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSyndicationUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSyndicationVisible
        {
            get
            {
                return _DateSyndicationVisible;
            }
            set
            {
                OnDateSyndicationVisibleChanging(value);
                ReportPropertyChanging("DateSyndicationVisible");
                _DateSyndicationVisible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSyndicationVisible");
                OnDateSyndicationVisibleChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSyndicationVisible;
        partial void OnDateSyndicationVisibleChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSyndicationVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.String _Active;
        partial void OnActiveChanging(global::System.String value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmbedCode
        {
            get
            {
                return _EmbedCode;
            }
            set
            {
                OnEmbedCodeChanging(value);
                ReportPropertyChanging("EmbedCode");
                _EmbedCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmbedCode");
                OnEmbedCodeChanged();
            }
        }
        private global::System.String _EmbedCode;
        partial void OnEmbedCodeChanging(global::System.String value);
        partial void OnEmbedCodeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_SourceForgeModel", "FK_MediaStorage_Media", "MediaStorage")]
        public EntityCollection<MediaStorage> MediaStorages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MediaStorage>("ContentServices_SourceForgeModel.FK_MediaStorage_Media", "MediaStorage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MediaStorage>("ContentServices_SourceForgeModel.FK_MediaStorage_Media", "MediaStorage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_SourceForgeModel", Name="MediaStorage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MediaStorage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MediaStorage object.
        /// </summary>
        /// <param name="mediaID">Initial value of the MediaID property.</param>
        /// <param name="storageID">Initial value of the StorageID property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static MediaStorage CreateMediaStorage(global::System.Int32 mediaID, global::System.Int32 storageID, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime)
        {
            MediaStorage mediaStorage = new MediaStorage();
            mediaStorage.MediaID = mediaID;
            mediaStorage.StorageID = storageID;
            mediaStorage.CreatedByGuid = createdByGuid;
            mediaStorage.CreatedDateTime = createdDateTime;
            mediaStorage.ModifiedByGuid = modifiedByGuid;
            mediaStorage.ModifiedDateTime = modifiedDateTime;
            return mediaStorage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MediaID
        {
            get
            {
                return _MediaID;
            }
            set
            {
                if (_MediaID != value)
                {
                    OnMediaIDChanging(value);
                    ReportPropertyChanging("MediaID");
                    _MediaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MediaID");
                    OnMediaIDChanged();
                }
            }
        }
        private global::System.Int32 _MediaID;
        partial void OnMediaIDChanging(global::System.Int32 value);
        partial void OnMediaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StorageID
        {
            get
            {
                return _StorageID;
            }
            set
            {
                if (_StorageID != value)
                {
                    OnStorageIDChanging(value);
                    ReportPropertyChanging("StorageID");
                    _StorageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StorageID");
                    OnStorageIDChanged();
                }
            }
        }
        private global::System.Int32 _StorageID;
        partial void OnStorageIDChanging(global::System.Int32 value);
        partial void OnStorageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_SourceForgeModel", "FK_MediaStorage_Storage", "Storage")]
        public Storage Storage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Storage>("ContentServices_SourceForgeModel.FK_MediaStorage_Storage", "Storage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Storage>("ContentServices_SourceForgeModel.FK_MediaStorage_Storage", "Storage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Storage> StorageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Storage>("ContentServices_SourceForgeModel.FK_MediaStorage_Storage", "Storage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Storage>("ContentServices_SourceForgeModel.FK_MediaStorage_Storage", "Storage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_SourceForgeModel", "FK_MediaStorage_Media", "Media")]
        public Medias Medium
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medias>("ContentServices_SourceForgeModel.FK_MediaStorage_Media", "Media").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medias>("ContentServices_SourceForgeModel.FK_MediaStorage_Media", "Media").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Medias> MediumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Medias>("ContentServices_SourceForgeModel.FK_MediaStorage_Media", "Media");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Medias>("ContentServices_SourceForgeModel.FK_MediaStorage_Media", "Media", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ContentServices_SourceForgeModel", Name="Storage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Storage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Storage object.
        /// </summary>
        /// <param name="storageID">Initial value of the StorageID property.</param>
        /// <param name="createdByGuid">Initial value of the CreatedByGuid property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedByGuid">Initial value of the ModifiedByGuid property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static Storage CreateStorage(global::System.Int32 storageID, global::System.Guid createdByGuid, global::System.DateTime createdDateTime, global::System.Guid modifiedByGuid, global::System.DateTime modifiedDateTime)
        {
            Storage storage = new Storage();
            storage.StorageID = storageID;
            storage.CreatedByGuid = createdByGuid;
            storage.CreatedDateTime = createdDateTime;
            storage.ModifiedByGuid = modifiedByGuid;
            storage.ModifiedDateTime = modifiedDateTime;
            return storage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StorageID
        {
            get
            {
                return _StorageID;
            }
            set
            {
                if (_StorageID != value)
                {
                    OnStorageIDChanging(value);
                    ReportPropertyChanging("StorageID");
                    _StorageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StorageID");
                    OnStorageIDChanged();
                }
            }
        }
        private global::System.Int32 _StorageID;
        partial void OnStorageIDChanging(global::System.Int32 value);
        partial void OnStorageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ByteStream
        {
            get
            {
                return StructuralObject.GetValidValue(_ByteStream);
            }
            set
            {
                OnByteStreamChanging(value);
                ReportPropertyChanging("ByteStream");
                _ByteStream = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ByteStream");
                OnByteStreamChanged();
            }
        }
        private global::System.Byte[] _ByteStream;
        partial void OnByteStreamChanging(global::System.Byte[] value);
        partial void OnByteStreamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileExtension
        {
            get
            {
                return _FileExtension;
            }
            set
            {
                OnFileExtensionChanging(value);
                ReportPropertyChanging("FileExtension");
                _FileExtension = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileExtension");
                OnFileExtensionChanged();
            }
        }
        private global::System.String _FileExtension;
        partial void OnFileExtensionChanging(global::System.String value);
        partial void OnFileExtensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CreatedByGuid
        {
            get
            {
                return _CreatedByGuid;
            }
            set
            {
                OnCreatedByGuidChanging(value);
                ReportPropertyChanging("CreatedByGuid");
                _CreatedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByGuid");
                OnCreatedByGuidChanged();
            }
        }
        private global::System.Guid _CreatedByGuid;
        partial void OnCreatedByGuidChanging(global::System.Guid value);
        partial void OnCreatedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ModifiedByGuid
        {
            get
            {
                return _ModifiedByGuid;
            }
            set
            {
                OnModifiedByGuidChanging(value);
                ReportPropertyChanging("ModifiedByGuid");
                _ModifiedByGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByGuid");
                OnModifiedByGuidChanged();
            }
        }
        private global::System.Guid _ModifiedByGuid;
        partial void OnModifiedByGuidChanging(global::System.Guid value);
        partial void OnModifiedByGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ContentServices_SourceForgeModel", "FK_MediaStorage_Storage", "MediaStorage")]
        public EntityCollection<MediaStorage> MediaStorages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MediaStorage>("ContentServices_SourceForgeModel.FK_MediaStorage_Storage", "MediaStorage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MediaStorage>("ContentServices_SourceForgeModel.FK_MediaStorage_Storage", "MediaStorage", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
