// Copyright [2015] [Centers for Disease Control and Prevention] 
// Licensed under the CDC Custom Open Source License 1 (the 'License'); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at
// 
//   http://t.cdc.gov/O4O
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Gov.Hhs.Cdc.DataProvider.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DataDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DataDbEntities object using the connection string found in the 'DataDbEntities' section of the application configuration file.
        /// </summary>
        public DataDbEntities() : base("name=DataDbEntities", "DataDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataDbEntities object.
        /// </summary>
        public DataDbEntities(string connectionString) : base(connectionString, "DataDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DataDbEntities object.
        /// </summary>
        public DataDbEntities(EntityConnection connection) : base(connection, "DataDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProxyCacheAppKey> ProxyCacheAppKeys
        {
            get
            {
                if ((_ProxyCacheAppKeys == null))
                {
                    _ProxyCacheAppKeys = base.CreateObjectSet<ProxyCacheAppKey>("ProxyCacheAppKeys");
                }
                return _ProxyCacheAppKeys;
            }
        }
        private ObjectSet<ProxyCacheAppKey> _ProxyCacheAppKeys;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProxyCache> ProxyCaches
        {
            get
            {
                if ((_ProxyCaches == null))
                {
                    _ProxyCaches = base.CreateObjectSet<ProxyCache>("ProxyCaches");
                }
                return _ProxyCaches;
            }
        }
        private ObjectSet<ProxyCache> _ProxyCaches;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProxyCacheAppKeys EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProxyCacheAppKeys(ProxyCacheAppKey proxyCacheAppKey)
        {
            base.AddObject("ProxyCacheAppKeys", proxyCacheAppKey);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProxyCaches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProxyCaches(ProxyCache proxyCache)
        {
            base.AddObject("ProxyCaches", proxyCache);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataDbModel", Name="ProxyCache")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProxyCache : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProxyCache object.
        /// </summary>
        /// <param name="proxyCacheID">Initial value of the ProxyCacheID property.</param>
        /// <param name="proxyCacheURL">Initial value of the ProxyCacheURL property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        /// <param name="expirationDateTime">Initial value of the ExpirationDateTime property.</param>
        /// <param name="expirationInterval">Initial value of the ExpirationInterval property.</param>
        /// <param name="needsRefresh">Initial value of the NeedsRefresh property.</param>
        public static ProxyCache CreateProxyCache(global::System.Int32 proxyCacheID, global::System.String proxyCacheURL, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime, global::System.DateTime expirationDateTime, global::System.String expirationInterval, global::System.Boolean needsRefresh)
        {
            ProxyCache proxyCache = new ProxyCache();
            proxyCache.ProxyCacheID = proxyCacheID;
            proxyCache.ProxyCacheURL = proxyCacheURL;
            proxyCache.CreatedDateTime = createdDateTime;
            proxyCache.ModifiedDateTime = modifiedDateTime;
            proxyCache.ExpirationDateTime = expirationDateTime;
            proxyCache.ExpirationInterval = expirationInterval;
            proxyCache.NeedsRefresh = needsRefresh;
            return proxyCache;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProxyCacheID
        {
            get
            {
                return _ProxyCacheID;
            }
            set
            {
                if (_ProxyCacheID != value)
                {
                    OnProxyCacheIDChanging(value);
                    ReportPropertyChanging("ProxyCacheID");
                    _ProxyCacheID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProxyCacheID");
                    OnProxyCacheIDChanged();
                }
            }
        }
        private global::System.Int32 _ProxyCacheID;
        partial void OnProxyCacheIDChanging(global::System.Int32 value);
        partial void OnProxyCacheIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProxyCacheURL
        {
            get
            {
                return _ProxyCacheURL;
            }
            set
            {
                OnProxyCacheURLChanging(value);
                ReportPropertyChanging("ProxyCacheURL");
                _ProxyCacheURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProxyCacheURL");
                OnProxyCacheURLChanged();
            }
        }
        private global::System.String _ProxyCacheURL;
        partial void OnProxyCacheURLChanging(global::System.String value);
        partial void OnProxyCacheURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataSetID
        {
            get
            {
                return _DataSetID;
            }
            set
            {
                OnDataSetIDChanging(value);
                ReportPropertyChanging("DataSetID");
                _DataSetID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataSetID");
                OnDataSetIDChanged();
            }
        }
        private global::System.String _DataSetID;
        partial void OnDataSetIDChanging(global::System.String value);
        partial void OnDataSetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpirationDateTime
        {
            get
            {
                return _ExpirationDateTime;
            }
            set
            {
                OnExpirationDateTimeChanging(value);
                ReportPropertyChanging("ExpirationDateTime");
                _ExpirationDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDateTime");
                OnExpirationDateTimeChanged();
            }
        }
        private global::System.DateTime _ExpirationDateTime;
        partial void OnExpirationDateTimeChanging(global::System.DateTime value);
        partial void OnExpirationDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExpirationInterval
        {
            get
            {
                return _ExpirationInterval;
            }
            set
            {
                OnExpirationIntervalChanging(value);
                ReportPropertyChanging("ExpirationInterval");
                _ExpirationInterval = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExpirationInterval");
                OnExpirationIntervalChanged();
            }
        }
        private global::System.String _ExpirationInterval;
        partial void OnExpirationIntervalChanging(global::System.String value);
        partial void OnExpirationIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean NeedsRefresh
        {
            get
            {
                return _NeedsRefresh;
            }
            set
            {
                OnNeedsRefreshChanging(value);
                ReportPropertyChanging("NeedsRefresh");
                _NeedsRefresh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NeedsRefresh");
                OnNeedsRefreshChanged();
            }
        }
        private global::System.Boolean _NeedsRefresh;
        partial void OnNeedsRefreshChanging(global::System.Boolean value);
        partial void OnNeedsRefreshChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] HashedKey
        {
            get
            {
                return StructuralObject.GetValidValue(_HashedKey);
            }
            set
            {
                OnHashedKeyChanging(value);
                ReportPropertyChanging("HashedKey");
                _HashedKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HashedKey");
                OnHashedKeyChanged();
            }
        }
        private global::System.Byte[] _HashedKey;
        partial void OnHashedKeyChanging(global::System.Byte[] value);
        partial void OnHashedKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DataFailures
        {
            get
            {
                return _DataFailures;
            }
            set
            {
                OnDataFailuresChanging(value);
                ReportPropertyChanging("DataFailures");
                _DataFailures = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataFailures");
                OnDataFailuresChanged();
            }
        }
        private Nullable<global::System.Int32> _DataFailures;
        partial void OnDataFailuresChanging(Nullable<global::System.Int32> value);
        partial void OnDataFailuresChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataDbModel", Name="ProxyCacheAppKey")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProxyCacheAppKey : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProxyCacheAppKey object.
        /// </summary>
        /// <param name="proxyCacheAppKeyID">Initial value of the ProxyCacheAppKeyID property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="createdDateTime">Initial value of the CreatedDateTime property.</param>
        /// <param name="modifiedDateTime">Initial value of the ModifiedDateTime property.</param>
        public static ProxyCacheAppKey CreateProxyCacheAppKey(global::System.String proxyCacheAppKeyID, global::System.Boolean active, global::System.DateTime createdDateTime, global::System.DateTime modifiedDateTime)
        {
            ProxyCacheAppKey proxyCacheAppKey = new ProxyCacheAppKey();
            proxyCacheAppKey.ProxyCacheAppKeyID = proxyCacheAppKeyID;
            proxyCacheAppKey.Active = active;
            proxyCacheAppKey.CreatedDateTime = createdDateTime;
            proxyCacheAppKey.ModifiedDateTime = modifiedDateTime;
            return proxyCacheAppKey;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProxyCacheAppKeyID
        {
            get
            {
                return _ProxyCacheAppKeyID;
            }
            set
            {
                if (_ProxyCacheAppKeyID != value)
                {
                    OnProxyCacheAppKeyIDChanging(value);
                    ReportPropertyChanging("ProxyCacheAppKeyID");
                    _ProxyCacheAppKeyID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ProxyCacheAppKeyID");
                    OnProxyCacheAppKeyIDChanged();
                }
            }
        }
        private global::System.String _ProxyCacheAppKeyID;
        partial void OnProxyCacheAppKeyIDChanging(global::System.String value);
        partial void OnProxyCacheAppKeyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDateTime
        {
            get
            {
                return _CreatedDateTime;
            }
            set
            {
                OnCreatedDateTimeChanging(value);
                ReportPropertyChanging("CreatedDateTime");
                _CreatedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDateTime");
                OnCreatedDateTimeChanged();
            }
        }
        private global::System.DateTime _CreatedDateTime;
        partial void OnCreatedDateTimeChanging(global::System.DateTime value);
        partial void OnCreatedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ModifiedDateTime
        {
            get
            {
                return _ModifiedDateTime;
            }
            set
            {
                OnModifiedDateTimeChanging(value);
                ReportPropertyChanging("ModifiedDateTime");
                _ModifiedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDateTime");
                OnModifiedDateTimeChanged();
            }
        }
        private global::System.DateTime _ModifiedDateTime;
        partial void OnModifiedDateTimeChanging(global::System.DateTime value);
        partial void OnModifiedDateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
